// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type CompliancePolicy struct {
	Profile     ComplianceProfile `json:"profile"`
	Version     string            `json:"version"`
	Status      PolicyStatus      `json:"status"`
	EffectiveAt string            `json:"effectiveAt"`
	Reason      *string           `json:"reason,omitempty"`
}

type ConfirmMFAInput struct {
	Code string `json:"code"`
}

type Consent struct {
	ID             string         `json:"id"`
	Purpose        ConsentPurpose `json:"purpose"`
	PolicyVersion  string         `json:"policyVersion"`
	GrantedAt      string         `json:"grantedAt"`
	WithdrawnAt    *string        `json:"withdrawnAt,omitempty"`
	OrganizationID *string        `json:"organizationId,omitempty"`
}

type CreateOrganizationInput struct {
	Name              string            `json:"name"`
	ComplianceProfile ComplianceProfile `json:"complianceProfile"`
}

type GrantConsentInput struct {
	Purpose        ConsentPurpose `json:"purpose"`
	OrganizationID *string        `json:"organizationId,omitempty"`
}

type InviteMemberInput struct {
	OrganizationID string  `json:"organizationId"`
	Email          string  `json:"email"`
	Role           OrgRole `json:"role"`
}

type LoginInput struct {
	Email             string `json:"email"`
	Password          string `json:"password"`
	DeviceFingerprint string `json:"deviceFingerprint"`
}

type LoginPayload struct {
	Status LoginStatus `json:"status"`
	User   *User       `json:"user,omitempty"`
}

type MFASetupPayload struct {
	Secret     string `json:"secret"`
	OtpauthURL string `json:"otpauthUrl"`
}

type Mutation struct {
}

type Organization struct {
	ID                      string            `json:"id"`
	Name                    string            `json:"name"`
	Type                    OrgType           `json:"type"`
	ComplianceProfile       ComplianceProfile `json:"complianceProfile"`
	CompliancePolicyVersion string            `json:"compliancePolicyVersion"`
}

type OrganizationMember struct {
	UserID    string  `json:"userId"`
	Email     string  `json:"email"`
	Role      OrgRole `json:"role"`
	JoinedAt  string  `json:"joinedAt"`
	InvitedAt string  `json:"invitedAt"`
}

type PublishCompliancePolicyInput struct {
	OrganizationID    string            `json:"organizationId"`
	ComplianceProfile ComplianceProfile `json:"complianceProfile"`
	Version           string            `json:"version"`
	Reason            string            `json:"reason"`
}

type Query struct {
}

type RegisterInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type RegisterPayload struct {
	Message string `json:"message"`
}

type RemoveMemberInput struct {
	OrganizationID string `json:"organizationId"`
	UserID         string `json:"userId"`
}

type UpdateComplianceProfileInput struct {
	OrganizationID    string            `json:"organizationId"`
	ComplianceProfile ComplianceProfile `json:"complianceProfile"`
}

type UpdateMemberRoleInput struct {
	OrganizationID string  `json:"organizationId"`
	UserID         string  `json:"userId"`
	Role           OrgRole `json:"role"`
}

type User struct {
	ID            string `json:"id"`
	Email         string `json:"email"`
	EmailVerified bool   `json:"emailVerified"`
	MfaEnabled    bool   `json:"mfaEnabled"`
	PersonalOrgID string `json:"personalOrgId"`
}

type VerifyDeviceInput struct {
	Code              string `json:"code"`
	DeviceFingerprint string `json:"deviceFingerprint"`
}

type VerifyLoginMFAInput struct {
	Code              string `json:"code"`
	DeviceFingerprint string `json:"deviceFingerprint"`
}

type WithdrawConsentInput struct {
	Purpose        ConsentPurpose `json:"purpose"`
	OrganizationID *string        `json:"organizationId,omitempty"`
}

type Workspace struct {
	OrganizationID string  `json:"organizationId"`
	Name           string  `json:"name"`
	Type           OrgType `json:"type"`
	Role           OrgRole `json:"role"`
}

type ComplianceProfile string

const (
	ComplianceProfileKVKK ComplianceProfile = "KVKK"
	ComplianceProfileGdpr ComplianceProfile = "GDPR"
	ComplianceProfileBoth ComplianceProfile = "BOTH"
)

var AllComplianceProfile = []ComplianceProfile{
	ComplianceProfileKVKK,
	ComplianceProfileGdpr,
	ComplianceProfileBoth,
}

func (e ComplianceProfile) IsValid() bool {
	switch e {
	case ComplianceProfileKVKK, ComplianceProfileGdpr, ComplianceProfileBoth:
		return true
	}
	return false
}

func (e ComplianceProfile) String() string {
	return string(e)
}

func (e *ComplianceProfile) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ComplianceProfile(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ComplianceProfile", str)
	}
	return nil
}

func (e ComplianceProfile) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ComplianceProfile) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ComplianceProfile) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ConsentPurpose string

const (
	ConsentPurposeRegistration   ConsentPurpose = "REGISTRATION"
	ConsentPurposeOrgMembership  ConsentPurpose = "ORG_MEMBERSHIP"
	ConsentPurposeDataProcessing ConsentPurpose = "DATA_PROCESSING"
)

var AllConsentPurpose = []ConsentPurpose{
	ConsentPurposeRegistration,
	ConsentPurposeOrgMembership,
	ConsentPurposeDataProcessing,
}

func (e ConsentPurpose) IsValid() bool {
	switch e {
	case ConsentPurposeRegistration, ConsentPurposeOrgMembership, ConsentPurposeDataProcessing:
		return true
	}
	return false
}

func (e ConsentPurpose) String() string {
	return string(e)
}

func (e *ConsentPurpose) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ConsentPurpose(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ConsentPurpose", str)
	}
	return nil
}

func (e ConsentPurpose) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ConsentPurpose) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ConsentPurpose) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type LoginStatus string

const (
	LoginStatusMfaSetupRequired           LoginStatus = "MFA_SETUP_REQUIRED"
	LoginStatusMfaRequired                LoginStatus = "MFA_REQUIRED"
	LoginStatusDeviceVerificationRequired LoginStatus = "DEVICE_VERIFICATION_REQUIRED"
	LoginStatusAuthenticated              LoginStatus = "AUTHENTICATED"
)

var AllLoginStatus = []LoginStatus{
	LoginStatusMfaSetupRequired,
	LoginStatusMfaRequired,
	LoginStatusDeviceVerificationRequired,
	LoginStatusAuthenticated,
}

func (e LoginStatus) IsValid() bool {
	switch e {
	case LoginStatusMfaSetupRequired, LoginStatusMfaRequired, LoginStatusDeviceVerificationRequired, LoginStatusAuthenticated:
		return true
	}
	return false
}

func (e LoginStatus) String() string {
	return string(e)
}

func (e *LoginStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LoginStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LoginStatus", str)
	}
	return nil
}

func (e LoginStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *LoginStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e LoginStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type OrgRole string

const (
	OrgRoleOwner   OrgRole = "OWNER"
	OrgRoleAdmin   OrgRole = "ADMIN"
	OrgRoleAnalyst OrgRole = "ANALYST"
	OrgRoleViewer  OrgRole = "VIEWER"
)

var AllOrgRole = []OrgRole{
	OrgRoleOwner,
	OrgRoleAdmin,
	OrgRoleAnalyst,
	OrgRoleViewer,
}

func (e OrgRole) IsValid() bool {
	switch e {
	case OrgRoleOwner, OrgRoleAdmin, OrgRoleAnalyst, OrgRoleViewer:
		return true
	}
	return false
}

func (e OrgRole) String() string {
	return string(e)
}

func (e *OrgRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrgRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrgRole", str)
	}
	return nil
}

func (e OrgRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrgRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrgRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type OrgType string

const (
	OrgTypePersonal     OrgType = "PERSONAL"
	OrgTypeOrganization OrgType = "ORGANIZATION"
)

var AllOrgType = []OrgType{
	OrgTypePersonal,
	OrgTypeOrganization,
}

func (e OrgType) IsValid() bool {
	switch e {
	case OrgTypePersonal, OrgTypeOrganization:
		return true
	}
	return false
}

func (e OrgType) String() string {
	return string(e)
}

func (e *OrgType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrgType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrgType", str)
	}
	return nil
}

func (e OrgType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrgType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrgType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PolicyStatus string

const (
	PolicyStatusDraft     PolicyStatus = "DRAFT"
	PolicyStatusPublished PolicyStatus = "PUBLISHED"
	PolicyStatusArchived  PolicyStatus = "ARCHIVED"
)

var AllPolicyStatus = []PolicyStatus{
	PolicyStatusDraft,
	PolicyStatusPublished,
	PolicyStatusArchived,
}

func (e PolicyStatus) IsValid() bool {
	switch e {
	case PolicyStatusDraft, PolicyStatusPublished, PolicyStatusArchived:
		return true
	}
	return false
}

func (e PolicyStatus) String() string {
	return string(e)
}

func (e *PolicyStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PolicyStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PolicyStatus", str)
	}
	return nil
}

func (e PolicyStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PolicyStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PolicyStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
