// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type ActivityLogEntry struct {
	ID         string  `json:"id"`
	Action     string  `json:"action"`
	ResourceID *string `json:"resourceId,omitempty"`
	IPAddress  *string `json:"ipAddress,omitempty"`
	UserAgent  *string `json:"userAgent,omitempty"`
	Timestamp  string  `json:"timestamp"`
}

type AgentRunEvent struct {
	ID             string                `json:"id"`
	OrganizationID string                `json:"organizationId"`
	AnalysisRunID  string                `json:"analysisRunId"`
	Sequence       int                   `json:"sequence"`
	Phase          string                `json:"phase"`
	ToolName       *string               `json:"toolName,omitempty"`
	Status         AgentEventStatus      `json:"status"`
	Metadata       []*EventMetadataEntry `json:"metadata"`
	TraceID        string                `json:"traceId"`
	Timestamp      string                `json:"timestamp"`
}

type AnalysisRun struct {
	ID                      string               `json:"id"`
	OrganizationID          string               `json:"organizationId"`
	ProductID               string               `json:"productId"`
	MarketplaceImportRunID  *string              `json:"marketplaceImportRunId,omitempty"`
	ClientRequestID         string               `json:"clientRequestId"`
	Status                  AnalysisRunStatus    `json:"status"`
	CurrentPhase            *string              `json:"currentPhase,omitempty"`
	TraceID                 string               `json:"traceId"`
	ConfigSnapshotID        string               `json:"configSnapshotId"`
	ToolRegistryVersion     string               `json:"toolRegistryVersion"`
	ToolPolicyVersion       string               `json:"toolPolicyVersion"`
	CompliancePolicyVersion string               `json:"compliancePolicyVersion"`
	PlannerVersion          string               `json:"plannerVersion"`
	IterationCount          int                  `json:"iterationCount"`
	TerminalError           *string              `json:"terminalError,omitempty"`
	TerminalReason          *string              `json:"terminalReason,omitempty"`
	StartedAt               *string              `json:"startedAt,omitempty"`
	CompletedAt             *string              `json:"completedAt,omitempty"`
	CreatedAt               string               `json:"createdAt"`
	UpdatedAt               string               `json:"updatedAt"`
	Evidence                []*Evidence          `json:"evidence"`
	SafetyFindings          []*SafetyFinding     `json:"safetyFindings"`
	Recalls                 []*RecallMatch       `json:"recalls"`
	ReviewInsights          []*ReviewInsight     `json:"reviewInsights"`
	FinalResult             *FinalAnalysisResult `json:"finalResult,omitempty"`
}

type BuildDatasetDraftInput struct {
	OrganizationID string `json:"organizationId"`
	Version        string `json:"version"`
}

type CancelAgentRunInput struct {
	OrganizationID string `json:"organizationId"`
	AnalysisRunID  string `json:"analysisRunId"`
}

type CompliancePolicy struct {
	Profile     ComplianceProfile `json:"profile"`
	Version     string            `json:"version"`
	Status      PolicyStatus      `json:"status"`
	EffectiveAt string            `json:"effectiveAt"`
	Reason      *string           `json:"reason,omitempty"`
}

type ConfirmMFAInput struct {
	Code       string  `json:"code"`
	SetupToken *string `json:"setupToken,omitempty"`
}

type Consent struct {
	ID             string         `json:"id"`
	Purpose        ConsentPurpose `json:"purpose"`
	PolicyVersion  string         `json:"policyVersion"`
	GrantedAt      string         `json:"grantedAt"`
	WithdrawnAt    *string        `json:"withdrawnAt,omitempty"`
	OrganizationID *string        `json:"organizationId,omitempty"`
}

type CreateLLMConfigurationDraftInput struct {
	OrganizationID       string  `json:"organizationId"`
	RoutingPolicyVersion *string `json:"routingPolicyVersion,omitempty"`
	PersonaKey           *string `json:"personaKey,omitempty"`
	PersonaVersion       *string `json:"personaVersion,omitempty"`
	DefaultModelKey      *string `json:"defaultModelKey,omitempty"`
	FallbackModelKey     *string `json:"fallbackModelKey,omitempty"`
	Reason               string  `json:"reason"`
}

type CreateOrganizationInput struct {
	Name              string            `json:"name"`
	ComplianceProfile ComplianceProfile `json:"complianceProfile"`
}

type CreateProductInput struct {
	OrganizationID  string            `json:"organizationId"`
	Name            string            `json:"name"`
	Brand           *string           `json:"brand,omitempty"`
	Category        *string           `json:"category,omitempty"`
	Description     *string           `json:"description,omitempty"`
	Source          MarketplaceSource `json:"source"`
	SourceProductID string            `json:"sourceProductId"`
	SourceURL       *string           `json:"sourceUrl,omitempty"`
	Sku             *string           `json:"sku,omitempty"`
}

type CreateProductPayload struct {
	Product      *Product `json:"product"`
	Deduplicated bool     `json:"deduplicated"`
}

type CreateUserExperienceInput struct {
	OrganizationID    string            `json:"organizationId"`
	ProductID         string            `json:"productId"`
	UsageStatus       UsageStatus       `json:"usageStatus"`
	SatisfactionLevel SatisfactionLevel `json:"satisfactionLevel"`
	Rating            *int              `json:"rating,omitempty"`
	IssueType         *IssueType        `json:"issueType,omitempty"`
	Narrative         string            `json:"narrative"`
}

type DatasetEligibilitySummary struct {
	OrganizationID          string              `json:"organizationId"`
	TotalRecords            int                 `json:"totalRecords"`
	UgcCount                int                 `json:"ugcCount"`
	MarketplaceCount        int                 `json:"marketplaceCount"`
	EligibilityDistribution []*EligibilityCount `json:"eligibilityDistribution"`
	SourceDistribution      []*SourceCount      `json:"sourceDistribution"`
}

type DatasetVersion struct {
	ID                string               `json:"id"`
	OrganizationID    string               `json:"organizationId"`
	Version           string               `json:"version"`
	Status            DatasetVersionStatus `json:"status"`
	NormalizerVersion string               `json:"normalizerVersion"`
	ContentHash       *string              `json:"contentHash,omitempty"`
	CreatedAt         string               `json:"createdAt"`
}

type DeleteUserExperienceInput struct {
	OrganizationID string `json:"organizationId"`
	ExperienceID   string `json:"experienceId"`
}

type Device struct {
	ID           string         `json:"id"`
	Platform     ClientPlatform `json:"platform"`
	Label        string         `json:"label"`
	UserAgent    *string        `json:"userAgent,omitempty"`
	IPAddress    *string        `json:"ipAddress,omitempty"`
	AppVersion   *string        `json:"appVersion,omitempty"`
	Verified     bool           `json:"verified"`
	LastActiveAt string         `json:"lastActiveAt"`
	CreatedAt    string         `json:"createdAt"`
}

type EligibilityCount struct {
	Eligibility DatasetEligibility `json:"eligibility"`
	Count       int                `json:"count"`
}

type EventMetadataEntry struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Evidence struct {
	ID             string  `json:"id"`
	OrganizationID string  `json:"organizationId"`
	AnalysisRunID  string  `json:"analysisRunId"`
	ProductID      string  `json:"productId"`
	ClaimID        *string `json:"claimId,omitempty"`
	Source         string  `json:"source"`
	SourceType     string  `json:"sourceType"`
	Claim          string  `json:"claim"`
	Snippet        *string `json:"snippet,omitempty"`
	Reference      *string `json:"reference,omitempty"`
	SupportStatus  *string `json:"supportStatus,omitempty"`
	Reliability    float64 `json:"reliability"`
	Freshness      float64 `json:"freshness"`
	RetrievedAt    string  `json:"retrievedAt"`
	CreatedAt      string  `json:"createdAt"`
}

type FinalAnalysisResult struct {
	SchemaVersion      string   `json:"schemaVersion"`
	Summary            string   `json:"summary"`
	OverallRisk        string   `json:"overallRisk"`
	Confidence         float64  `json:"confidence"`
	Decision           string   `json:"decision"`
	Recommendation     string   `json:"recommendation"`
	Limitations        []string `json:"limitations"`
	HallucinationFlags []string `json:"hallucinationFlags"`
	CreatedAt          string   `json:"createdAt"`
}

type GrantConsentInput struct {
	Purpose        ConsentPurpose `json:"purpose"`
	OrganizationID *string        `json:"organizationId,omitempty"`
}

type InviteMemberInput struct {
	OrganizationID string  `json:"organizationId"`
	Email          string  `json:"email"`
	Role           OrgRole `json:"role"`
}

type LLMCall struct {
	ID                      string             `json:"id"`
	OrganizationID          string             `json:"organizationId"`
	ModelKey                string             `json:"modelKey"`
	PersonaKey              string             `json:"personaKey"`
	RoutingReason           string             `json:"routingReason"`
	FallbackUsed            bool               `json:"fallbackUsed"`
	InputTokens             int                `json:"inputTokens"`
	OutputTokens            int                `json:"outputTokens"`
	LatencyMs               int                `json:"latencyMs"`
	Status                  string             `json:"status"`
	ComplianceProfile       *ComplianceProfile `json:"complianceProfile,omitempty"`
	CompliancePolicyVersion *string            `json:"compliancePolicyVersion,omitempty"`
	ComplianceReflexVersion *string            `json:"complianceReflexVersion,omitempty"`
	SafetyResult            *string            `json:"safetyResult,omitempty"`
	CreatedAt               string             `json:"createdAt"`
}

type LLMConfiguration struct {
	ID                   string  `json:"id"`
	OrganizationID       *string `json:"organizationId,omitempty"`
	RoutingPolicyVersion string  `json:"routingPolicyVersion"`
	PersonaKey           string  `json:"personaKey"`
	PersonaVersion       string  `json:"personaVersion"`
	DefaultModelKey      string  `json:"defaultModelKey"`
	FallbackModelKey     string  `json:"fallbackModelKey"`
	PublishedAt          string  `json:"publishedAt"`
	Reason               string  `json:"reason"`
}

type LLMConfigurationDraft struct {
	ID                   string   `json:"id"`
	OrganizationID       string   `json:"organizationId"`
	Status               string   `json:"status"`
	RoutingPolicyVersion string   `json:"routingPolicyVersion"`
	PersonaKey           string   `json:"personaKey"`
	PersonaVersion       string   `json:"personaVersion"`
	DefaultModelKey      string   `json:"defaultModelKey"`
	FallbackModelKey     string   `json:"fallbackModelKey"`
	ValidationErrors     []string `json:"validationErrors"`
	UpdatedAt            string   `json:"updatedAt"`
}

type LLMModel struct {
	ID                  string   `json:"id"`
	ModelKey            string   `json:"modelKey"`
	DisplayName         string   `json:"displayName"`
	Status              string   `json:"status"`
	HealthStatus        string   `json:"healthStatus"`
	ContextWindowTokens int      `json:"contextWindowTokens"`
	DefaultForPlatform  bool     `json:"defaultForPlatform"`
	FallbackForPlatform bool     `json:"fallbackForPlatform"`
	SupportedTaskTypes  []string `json:"supportedTaskTypes"`
}

type LLMModelHealth struct {
	ModelKey     string `json:"modelKey"`
	DisplayName  string `json:"displayName"`
	HealthStatus string `json:"healthStatus"`
	ProviderKey  string `json:"providerKey"`
}

type LLMModelUsage struct {
	ModelKey         string  `json:"modelKey"`
	DisplayName      string  `json:"displayName"`
	CallCount        int     `json:"callCount"`
	InputTokens      int     `json:"inputTokens"`
	OutputTokens     int     `json:"outputTokens"`
	TotalTokens      int     `json:"totalTokens"`
	EstimatedCostUsd float64 `json:"estimatedCostUsd"`
}

type LLMOrgSettings struct {
	OrganizationID   string `json:"organizationId"`
	PersonaKey       string `json:"personaKey"`
	DefaultModelKey  string `json:"defaultModelKey"`
	FallbackModelKey string `json:"fallbackModelKey"`
}

type LLMPersona struct {
	ID          string `json:"id"`
	PersonaKey  string `json:"personaKey"`
	Version     string `json:"version"`
	Status      string `json:"status"`
	DisplayName string `json:"displayName"`
}

type LLMProvider struct {
	ID          string `json:"id"`
	ProviderKey string `json:"providerKey"`
	DisplayName string `json:"displayName"`
	Status      string `json:"status"`
}

type LLMRoutingPolicy struct {
	ID               string  `json:"id"`
	Version          string  `json:"version"`
	Status           string  `json:"status"`
	DefaultModelKey  string  `json:"defaultModelKey"`
	FallbackModelKey string  `json:"fallbackModelKey"`
	PublishedAt      *string `json:"publishedAt,omitempty"`
}

type LLMTestResult struct {
	CallID         string `json:"callId"`
	ModelKey       string `json:"modelKey"`
	FallbackUsed   bool   `json:"fallbackUsed"`
	EscalationUsed bool   `json:"escalationUsed"`
	RoutingReason  string `json:"routingReason"`
	PersonaKey     string `json:"personaKey"`
	PersonaVersion string `json:"personaVersion"`
	ContentPreview string `json:"contentPreview"`
	InputTokens    int    `json:"inputTokens"`
	OutputTokens   int    `json:"outputTokens"`
}

type LLMUsageDashboard struct {
	Summary     *LLMUsageSummary `json:"summary"`
	ByModel     []*LLMModelUsage `json:"byModel"`
	RecentCalls []*LLMCall       `json:"recentCalls"`
}

type LLMUsageSummary struct {
	CallCount        int     `json:"callCount"`
	InputTokens      int     `json:"inputTokens"`
	OutputTokens     int     `json:"outputTokens"`
	TotalTokens      int     `json:"totalTokens"`
	EstimatedCostUsd float64 `json:"estimatedCostUsd"`
	FallbackCount    int     `json:"fallbackCount"`
}

type LoginInput struct {
	Email             string          `json:"email"`
	Password          string          `json:"password"`
	DeviceFingerprint string          `json:"deviceFingerprint"`
	Platform          *ClientPlatform `json:"platform,omitempty"`
	AppVersion        *string         `json:"appVersion,omitempty"`
	TurnstileToken    *string         `json:"turnstileToken,omitempty"`
}

type LoginPayload struct {
	Status   LoginStatus      `json:"status"`
	User     *User            `json:"user,omitempty"`
	MfaSetup *MFASetupPayload `json:"mfaSetup,omitempty"`
}

type MFASetupPayload struct {
	Secret     string `json:"secret"`
	OtpauthURL string `json:"otpauthUrl"`
	SetupToken string `json:"setupToken"`
}

type MarketplaceImportRun struct {
	ID              string                  `json:"id"`
	OrganizationID  string                  `json:"organizationId"`
	Source          MarketplaceSource       `json:"source"`
	SourceURL       *string                 `json:"sourceUrl,omitempty"`
	AccessMode      AccessMode              `json:"accessMode"`
	Status          MarketplaceImportStatus `json:"status"`
	RecordsSeen     int                     `json:"recordsSeen"`
	RecordsAccepted int                     `json:"recordsAccepted"`
	RecordsRejected int                     `json:"recordsRejected"`
	ErrorCode       *string                 `json:"errorCode,omitempty"`
	ErrorMessage    *string                 `json:"errorMessage,omitempty"`
	CreatedAt       string                  `json:"createdAt"`
}

type MarketplaceReview struct {
	ID                 string             `json:"id"`
	OrganizationID     string             `json:"organizationId"`
	ProductID          string             `json:"productId"`
	Source             MarketplaceSource  `json:"source"`
	Rating             *float64           `json:"rating,omitempty"`
	ReviewText         string             `json:"reviewText"`
	ReviewDate         *string            `json:"reviewDate,omitempty"`
	Language           string             `json:"language"`
	ModerationStatus   ModerationStatus   `json:"moderationStatus"`
	DatasetEligibility DatasetEligibility `json:"datasetEligibility"`
	CreatedAt          string             `json:"createdAt"`
}

type ModerateUserExperienceInput struct {
	OrganizationID   string           `json:"organizationId"`
	ExperienceID     string           `json:"experienceId"`
	ModerationStatus ModerationStatus `json:"moderationStatus"`
	QualityStatus    *QualityStatus   `json:"qualityStatus,omitempty"`
}

type Mutation struct {
}

type Organization struct {
	ID                      string            `json:"id"`
	Name                    string            `json:"name"`
	Type                    OrgType           `json:"type"`
	ComplianceProfile       ComplianceProfile `json:"complianceProfile"`
	CompliancePolicyVersion string            `json:"compliancePolicyVersion"`
}

type OrganizationMember struct {
	UserID    string  `json:"userId"`
	Email     string  `json:"email"`
	Role      OrgRole `json:"role"`
	JoinedAt  string  `json:"joinedAt"`
	InvitedAt string  `json:"invitedAt"`
}

type Product struct {
	ID             string            `json:"id"`
	OrganizationID string            `json:"organizationId"`
	Name           *ProductFieldMeta `json:"name"`
	Brand          *ProductFieldMeta `json:"brand"`
	Category       *ProductFieldMeta `json:"category"`
	Description    *ProductFieldMeta `json:"description"`
	TargetAge      *ProductFieldMeta `json:"targetAge"`
	Materials      *ProductFieldMeta `json:"materials"`
	SafetyWarnings *ProductFieldMeta `json:"safetyWarnings"`
	CurrentPrice   *ProductFieldMeta `json:"currentPrice"`
	OriginalPrice  *ProductFieldMeta `json:"originalPrice"`
	Currency       *ProductFieldMeta `json:"currency"`
	Seller         *ProductFieldMeta `json:"seller"`
	Rating         *ProductFieldMeta `json:"rating"`
	ReviewCount    *ProductFieldMeta `json:"reviewCount"`
	Attributes     *ProductFieldMeta `json:"attributes"`
	ImageRefs      *ProductFieldMeta `json:"imageRefs"`
	StockStatus    *ProductFieldMeta `json:"stockStatus"`
	Sku            *ProductFieldMeta `json:"sku"`
	CreatedAt      string            `json:"createdAt"`
	UpdatedAt      string            `json:"updatedAt"`
}

type ProductFieldMeta struct {
	Value          *string  `json:"value,omitempty"`
	Missing        bool     `json:"missing"`
	MissingReason  *string  `json:"missingReason,omitempty"`
	Source         *string  `json:"source,omitempty"`
	SourceRecordID *string  `json:"sourceRecordId,omitempty"`
	Confidence     *float64 `json:"confidence,omitempty"`
	ExtractedAt    *string  `json:"extractedAt,omitempty"`
}

type PublishCompliancePolicyInput struct {
	OrganizationID    string            `json:"organizationId"`
	ComplianceProfile ComplianceProfile `json:"complianceProfile"`
	Version           string            `json:"version"`
	Reason            string            `json:"reason"`
}

type PublishLLMConfigurationInput struct {
	OrganizationID string `json:"organizationId"`
	DraftID        string `json:"draftId"`
	Reason         string `json:"reason"`
}

type Query struct {
}

type RecallMatch struct {
	Source         string  `json:"source"`
	SourceRecordID string  `json:"sourceRecordId"`
	Matched        bool    `json:"matched"`
	Confidence     float64 `json:"confidence"`
	Method         string  `json:"method"`
	Reference      *string `json:"reference,omitempty"`
	RequiresReview bool    `json:"requiresReview"`
}

type RegisterInput struct {
	Email          string  `json:"email"`
	Password       string  `json:"password"`
	TurnstileToken *string `json:"turnstileToken,omitempty"`
}

type RegisterPayload struct {
	Message string `json:"message"`
}

type RemoveMemberInput struct {
	OrganizationID string `json:"organizationId"`
	UserID         string `json:"userId"`
}

type ResendEmailVerificationInput struct {
	Email          string  `json:"email"`
	Password       string  `json:"password"`
	TurnstileToken *string `json:"turnstileToken,omitempty"`
}

type ReviewInsight struct {
	Topic   string `json:"topic"`
	Count   int    `json:"count"`
	Summary string `json:"summary"`
	Kind    string `json:"kind"`
}

type RollbackLLMConfigurationInput struct {
	OrganizationID string `json:"organizationId"`
	SnapshotID     string `json:"snapshotId"`
	Reason         string `json:"reason"`
}

type SafetyFinding struct {
	ID            string   `json:"id"`
	AnalysisRunID string   `json:"analysisRunId"`
	ProductID     string   `json:"productId"`
	Type          string   `json:"type"`
	Severity      string   `json:"severity"`
	Confidence    float64  `json:"confidence"`
	EvidenceIds   []string `json:"evidenceIds"`
	Rationale     string   `json:"rationale"`
	CreatedAt     string   `json:"createdAt"`
}

type SetOrganizationModelsInput struct {
	OrganizationID   string `json:"organizationId"`
	DefaultModelKey  string `json:"defaultModelKey"`
	FallbackModelKey string `json:"fallbackModelKey"`
}

type SetOrganizationPersonaInput struct {
	OrganizationID string `json:"organizationId"`
	PersonaKey     string `json:"personaKey"`
}

type SourceCount struct {
	RecordType string `json:"recordType"`
	Count      int    `json:"count"`
}

type StartAgentRunInput struct {
	OrganizationID         string  `json:"organizationId"`
	ProductID              string  `json:"productId"`
	MarketplaceImportRunID *string `json:"marketplaceImportRunId,omitempty"`
	ClientRequestID        string  `json:"clientRequestId"`
}

type StartMarketplaceFileImportInput struct {
	OrganizationID string            `json:"organizationId"`
	Source         MarketplaceSource `json:"source"`
	AccessMode     AccessMode        `json:"accessMode"`
	Filename       string            `json:"filename"`
	ContentBase64  string            `json:"contentBase64"`
	ContentType    string            `json:"contentType"`
}

type StartMarketplaceURLImportInput struct {
	OrganizationID string `json:"organizationId"`
	SourceURL      string `json:"sourceUrl"`
}

type TestLLMConfigurationInput struct {
	OrganizationID string  `json:"organizationId"`
	PersonaKey     *string `json:"personaKey,omitempty"`
	Prompt         string  `json:"prompt"`
}

type UpdateComplianceProfileInput struct {
	OrganizationID    string            `json:"organizationId"`
	ComplianceProfile ComplianceProfile `json:"complianceProfile"`
}

type UpdateMemberRoleInput struct {
	OrganizationID string  `json:"organizationId"`
	UserID         string  `json:"userId"`
	Role           OrgRole `json:"role"`
}

type UpdateUserExperienceInput struct {
	OrganizationID    string            `json:"organizationId"`
	ExperienceID      string            `json:"experienceId"`
	UsageStatus       UsageStatus       `json:"usageStatus"`
	SatisfactionLevel SatisfactionLevel `json:"satisfactionLevel"`
	Rating            *int              `json:"rating,omitempty"`
	IssueType         *IssueType        `json:"issueType,omitempty"`
	Narrative         string            `json:"narrative"`
}

type User struct {
	ID            string `json:"id"`
	Email         string `json:"email"`
	EmailVerified bool   `json:"emailVerified"`
	MfaEnabled    bool   `json:"mfaEnabled"`
	PersonalOrgID string `json:"personalOrgId"`
}

type UserExperience struct {
	ID                 string             `json:"id"`
	OrganizationID     string             `json:"organizationId"`
	ProductID          string             `json:"productId"`
	UserID             string             `json:"userId"`
	UsageStatus        UsageStatus        `json:"usageStatus"`
	SatisfactionLevel  SatisfactionLevel  `json:"satisfactionLevel"`
	Rating             *int               `json:"rating,omitempty"`
	IssueType          *IssueType         `json:"issueType,omitempty"`
	Narrative          string             `json:"narrative"`
	ModerationStatus   ModerationStatus   `json:"moderationStatus"`
	QualityStatus      QualityStatus      `json:"qualityStatus"`
	DatasetEligibility DatasetEligibility `json:"datasetEligibility"`
	CreatedAt          string             `json:"createdAt"`
	UpdatedAt          string             `json:"updatedAt"`
}

type ValidateLLMConfigurationInput struct {
	OrganizationID string `json:"organizationId"`
	DraftID        string `json:"draftId"`
}

type VerifyDeviceInput struct {
	Code              string `json:"code"`
	DeviceFingerprint string `json:"deviceFingerprint"`
}

type VerifyLoginEmailOTPInput struct {
	Code              string  `json:"code"`
	DeviceFingerprint string  `json:"deviceFingerprint"`
	TurnstileToken    *string `json:"turnstileToken,omitempty"`
}

type VerifyLoginMFAInput struct {
	Code              string `json:"code"`
	DeviceFingerprint string `json:"deviceFingerprint"`
}

type WithdrawConsentInput struct {
	Purpose        ConsentPurpose `json:"purpose"`
	OrganizationID *string        `json:"organizationId,omitempty"`
}

type Workspace struct {
	OrganizationID string  `json:"organizationId"`
	Name           string  `json:"name"`
	Type           OrgType `json:"type"`
	Role           OrgRole `json:"role"`
}

type AccessMode string

const (
	AccessModeAuthorizedAPI        AccessMode = "AUTHORIZED_API"
	AccessModePermittedPublicFetch AccessMode = "PERMITTED_PUBLIC_FETCH"
	AccessModeLicensedDataset      AccessMode = "LICENSED_DATASET"
	AccessModeCSVImport            AccessMode = "CSV_IMPORT"
	AccessModeJSONImport           AccessMode = "JSON_IMPORT"
	AccessModeUserProvidedFile     AccessMode = "USER_PROVIDED_FILE"
	AccessModeManualEntry          AccessMode = "MANUAL_ENTRY"
)

var AllAccessMode = []AccessMode{
	AccessModeAuthorizedAPI,
	AccessModePermittedPublicFetch,
	AccessModeLicensedDataset,
	AccessModeCSVImport,
	AccessModeJSONImport,
	AccessModeUserProvidedFile,
	AccessModeManualEntry,
}

func (e AccessMode) IsValid() bool {
	switch e {
	case AccessModeAuthorizedAPI, AccessModePermittedPublicFetch, AccessModeLicensedDataset, AccessModeCSVImport, AccessModeJSONImport, AccessModeUserProvidedFile, AccessModeManualEntry:
		return true
	}
	return false
}

func (e AccessMode) String() string {
	return string(e)
}

func (e *AccessMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AccessMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AccessMode", str)
	}
	return nil
}

func (e AccessMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AccessMode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AccessMode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AgentEventStatus string

const (
	AgentEventStatusRunning   AgentEventStatus = "RUNNING"
	AgentEventStatusCompleted AgentEventStatus = "COMPLETED"
	AgentEventStatusFailed    AgentEventStatus = "FAILED"
)

var AllAgentEventStatus = []AgentEventStatus{
	AgentEventStatusRunning,
	AgentEventStatusCompleted,
	AgentEventStatusFailed,
}

func (e AgentEventStatus) IsValid() bool {
	switch e {
	case AgentEventStatusRunning, AgentEventStatusCompleted, AgentEventStatusFailed:
		return true
	}
	return false
}

func (e AgentEventStatus) String() string {
	return string(e)
}

func (e *AgentEventStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AgentEventStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AgentEventStatus", str)
	}
	return nil
}

func (e AgentEventStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AgentEventStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AgentEventStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AnalysisRunStatus string

const (
	AnalysisRunStatusPending   AnalysisRunStatus = "PENDING"
	AnalysisRunStatusRunning   AnalysisRunStatus = "RUNNING"
	AnalysisRunStatusCompleted AnalysisRunStatus = "COMPLETED"
	AnalysisRunStatusFailed    AnalysisRunStatus = "FAILED"
	AnalysisRunStatusRejected  AnalysisRunStatus = "REJECTED"
)

var AllAnalysisRunStatus = []AnalysisRunStatus{
	AnalysisRunStatusPending,
	AnalysisRunStatusRunning,
	AnalysisRunStatusCompleted,
	AnalysisRunStatusFailed,
	AnalysisRunStatusRejected,
}

func (e AnalysisRunStatus) IsValid() bool {
	switch e {
	case AnalysisRunStatusPending, AnalysisRunStatusRunning, AnalysisRunStatusCompleted, AnalysisRunStatusFailed, AnalysisRunStatusRejected:
		return true
	}
	return false
}

func (e AnalysisRunStatus) String() string {
	return string(e)
}

func (e *AnalysisRunStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AnalysisRunStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AnalysisRunStatus", str)
	}
	return nil
}

func (e AnalysisRunStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AnalysisRunStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AnalysisRunStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ClientPlatform string

const (
	ClientPlatformWeb         ClientPlatform = "WEB"
	ClientPlatformElectronWin ClientPlatform = "ELECTRON_WIN"
	ClientPlatformElectronMac ClientPlatform = "ELECTRON_MAC"
)

var AllClientPlatform = []ClientPlatform{
	ClientPlatformWeb,
	ClientPlatformElectronWin,
	ClientPlatformElectronMac,
}

func (e ClientPlatform) IsValid() bool {
	switch e {
	case ClientPlatformWeb, ClientPlatformElectronWin, ClientPlatformElectronMac:
		return true
	}
	return false
}

func (e ClientPlatform) String() string {
	return string(e)
}

func (e *ClientPlatform) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ClientPlatform(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ClientPlatform", str)
	}
	return nil
}

func (e ClientPlatform) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ClientPlatform) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ClientPlatform) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ComplianceProfile string

const (
	ComplianceProfileKVKK ComplianceProfile = "KVKK"
	ComplianceProfileGdpr ComplianceProfile = "GDPR"
	ComplianceProfileBoth ComplianceProfile = "BOTH"
)

var AllComplianceProfile = []ComplianceProfile{
	ComplianceProfileKVKK,
	ComplianceProfileGdpr,
	ComplianceProfileBoth,
}

func (e ComplianceProfile) IsValid() bool {
	switch e {
	case ComplianceProfileKVKK, ComplianceProfileGdpr, ComplianceProfileBoth:
		return true
	}
	return false
}

func (e ComplianceProfile) String() string {
	return string(e)
}

func (e *ComplianceProfile) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ComplianceProfile(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ComplianceProfile", str)
	}
	return nil
}

func (e ComplianceProfile) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ComplianceProfile) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ComplianceProfile) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ConsentPurpose string

const (
	ConsentPurposeRegistration   ConsentPurpose = "REGISTRATION"
	ConsentPurposeOrgMembership  ConsentPurpose = "ORG_MEMBERSHIP"
	ConsentPurposeDataProcessing ConsentPurpose = "DATA_PROCESSING"
)

var AllConsentPurpose = []ConsentPurpose{
	ConsentPurposeRegistration,
	ConsentPurposeOrgMembership,
	ConsentPurposeDataProcessing,
}

func (e ConsentPurpose) IsValid() bool {
	switch e {
	case ConsentPurposeRegistration, ConsentPurposeOrgMembership, ConsentPurposeDataProcessing:
		return true
	}
	return false
}

func (e ConsentPurpose) String() string {
	return string(e)
}

func (e *ConsentPurpose) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ConsentPurpose(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ConsentPurpose", str)
	}
	return nil
}

func (e ConsentPurpose) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ConsentPurpose) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ConsentPurpose) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DatasetEligibility string

const (
	DatasetEligibilityTrainingApproved DatasetEligibility = "TRAINING_APPROVED"
	DatasetEligibilityEvalOnly         DatasetEligibility = "EVAL_ONLY"
	DatasetEligibilityAnalysisOnly     DatasetEligibility = "ANALYSIS_ONLY"
	DatasetEligibilityQuarantined      DatasetEligibility = "QUARANTINED"
	DatasetEligibilityRejected         DatasetEligibility = "REJECTED"
)

var AllDatasetEligibility = []DatasetEligibility{
	DatasetEligibilityTrainingApproved,
	DatasetEligibilityEvalOnly,
	DatasetEligibilityAnalysisOnly,
	DatasetEligibilityQuarantined,
	DatasetEligibilityRejected,
}

func (e DatasetEligibility) IsValid() bool {
	switch e {
	case DatasetEligibilityTrainingApproved, DatasetEligibilityEvalOnly, DatasetEligibilityAnalysisOnly, DatasetEligibilityQuarantined, DatasetEligibilityRejected:
		return true
	}
	return false
}

func (e DatasetEligibility) String() string {
	return string(e)
}

func (e *DatasetEligibility) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DatasetEligibility(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DatasetEligibility", str)
	}
	return nil
}

func (e DatasetEligibility) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DatasetEligibility) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DatasetEligibility) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DatasetVersionStatus string

const (
	DatasetVersionStatusDraft DatasetVersionStatus = "DRAFT"
)

var AllDatasetVersionStatus = []DatasetVersionStatus{
	DatasetVersionStatusDraft,
}

func (e DatasetVersionStatus) IsValid() bool {
	switch e {
	case DatasetVersionStatusDraft:
		return true
	}
	return false
}

func (e DatasetVersionStatus) String() string {
	return string(e)
}

func (e *DatasetVersionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DatasetVersionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DatasetVersionStatus", str)
	}
	return nil
}

func (e DatasetVersionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DatasetVersionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DatasetVersionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type IssueType string

const (
	IssueTypeDurability               IssueType = "DURABILITY"
	IssueTypeBreakage                 IssueType = "BREAKAGE"
	IssueTypeAgeSizeMismatch          IssueType = "AGE_SIZE_MISMATCH"
	IssueTypeMaterial                 IssueType = "MATERIAL"
	IssueTypeOdor                     IssueType = "ODOR"
	IssueTypePackaging                IssueType = "PACKAGING"
	IssueTypeUsability                IssueType = "USABILITY"
	IssueTypeQuality                  IssueType = "QUALITY"
	IssueTypeSafetyRelatedObservation IssueType = "SAFETY_RELATED_OBSERVATION"
	IssueTypeOther                    IssueType = "OTHER"
)

var AllIssueType = []IssueType{
	IssueTypeDurability,
	IssueTypeBreakage,
	IssueTypeAgeSizeMismatch,
	IssueTypeMaterial,
	IssueTypeOdor,
	IssueTypePackaging,
	IssueTypeUsability,
	IssueTypeQuality,
	IssueTypeSafetyRelatedObservation,
	IssueTypeOther,
}

func (e IssueType) IsValid() bool {
	switch e {
	case IssueTypeDurability, IssueTypeBreakage, IssueTypeAgeSizeMismatch, IssueTypeMaterial, IssueTypeOdor, IssueTypePackaging, IssueTypeUsability, IssueTypeQuality, IssueTypeSafetyRelatedObservation, IssueTypeOther:
		return true
	}
	return false
}

func (e IssueType) String() string {
	return string(e)
}

func (e *IssueType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = IssueType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid IssueType", str)
	}
	return nil
}

func (e IssueType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *IssueType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e IssueType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type LoginStatus string

const (
	LoginStatusEmailOtpRequired           LoginStatus = "EMAIL_OTP_REQUIRED"
	LoginStatusMfaSetupRequired           LoginStatus = "MFA_SETUP_REQUIRED"
	LoginStatusMfaRequired                LoginStatus = "MFA_REQUIRED"
	LoginStatusDeviceVerificationRequired LoginStatus = "DEVICE_VERIFICATION_REQUIRED"
	LoginStatusAuthenticated              LoginStatus = "AUTHENTICATED"
)

var AllLoginStatus = []LoginStatus{
	LoginStatusEmailOtpRequired,
	LoginStatusMfaSetupRequired,
	LoginStatusMfaRequired,
	LoginStatusDeviceVerificationRequired,
	LoginStatusAuthenticated,
}

func (e LoginStatus) IsValid() bool {
	switch e {
	case LoginStatusEmailOtpRequired, LoginStatusMfaSetupRequired, LoginStatusMfaRequired, LoginStatusDeviceVerificationRequired, LoginStatusAuthenticated:
		return true
	}
	return false
}

func (e LoginStatus) String() string {
	return string(e)
}

func (e *LoginStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LoginStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LoginStatus", str)
	}
	return nil
}

func (e LoginStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *LoginStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e LoginStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MarketplaceImportStatus string

const (
	MarketplaceImportStatusPending          MarketplaceImportStatus = "PENDING"
	MarketplaceImportStatusRunning          MarketplaceImportStatus = "RUNNING"
	MarketplaceImportStatusSucceeded        MarketplaceImportStatus = "SUCCEEDED"
	MarketplaceImportStatusPartial          MarketplaceImportStatus = "PARTIAL"
	MarketplaceImportStatusFailed           MarketplaceImportStatus = "FAILED"
	MarketplaceImportStatusRejectedByPolicy MarketplaceImportStatus = "REJECTED_BY_POLICY"
)

var AllMarketplaceImportStatus = []MarketplaceImportStatus{
	MarketplaceImportStatusPending,
	MarketplaceImportStatusRunning,
	MarketplaceImportStatusSucceeded,
	MarketplaceImportStatusPartial,
	MarketplaceImportStatusFailed,
	MarketplaceImportStatusRejectedByPolicy,
}

func (e MarketplaceImportStatus) IsValid() bool {
	switch e {
	case MarketplaceImportStatusPending, MarketplaceImportStatusRunning, MarketplaceImportStatusSucceeded, MarketplaceImportStatusPartial, MarketplaceImportStatusFailed, MarketplaceImportStatusRejectedByPolicy:
		return true
	}
	return false
}

func (e MarketplaceImportStatus) String() string {
	return string(e)
}

func (e *MarketplaceImportStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MarketplaceImportStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MarketplaceImportStatus", str)
	}
	return nil
}

func (e MarketplaceImportStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MarketplaceImportStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MarketplaceImportStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MarketplaceSource string

const (
	MarketplaceSourceHepsiburada MarketplaceSource = "HEPSIBURADA"
	MarketplaceSourceTrendyol    MarketplaceSource = "TRENDYOL"
	MarketplaceSourceAmazon      MarketplaceSource = "AMAZON"
	MarketplaceSourceN11         MarketplaceSource = "N11"
	MarketplaceSourceOther       MarketplaceSource = "OTHER"
	MarketplaceSourceMiyuna      MarketplaceSource = "MIYUNA"
)

var AllMarketplaceSource = []MarketplaceSource{
	MarketplaceSourceHepsiburada,
	MarketplaceSourceTrendyol,
	MarketplaceSourceAmazon,
	MarketplaceSourceN11,
	MarketplaceSourceOther,
	MarketplaceSourceMiyuna,
}

func (e MarketplaceSource) IsValid() bool {
	switch e {
	case MarketplaceSourceHepsiburada, MarketplaceSourceTrendyol, MarketplaceSourceAmazon, MarketplaceSourceN11, MarketplaceSourceOther, MarketplaceSourceMiyuna:
		return true
	}
	return false
}

func (e MarketplaceSource) String() string {
	return string(e)
}

func (e *MarketplaceSource) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MarketplaceSource(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MarketplaceSource", str)
	}
	return nil
}

func (e MarketplaceSource) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MarketplaceSource) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MarketplaceSource) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ModerationStatus string

const (
	ModerationStatusPending  ModerationStatus = "PENDING"
	ModerationStatusApproved ModerationStatus = "APPROVED"
	ModerationStatusRejected ModerationStatus = "REJECTED"
)

var AllModerationStatus = []ModerationStatus{
	ModerationStatusPending,
	ModerationStatusApproved,
	ModerationStatusRejected,
}

func (e ModerationStatus) IsValid() bool {
	switch e {
	case ModerationStatusPending, ModerationStatusApproved, ModerationStatusRejected:
		return true
	}
	return false
}

func (e ModerationStatus) String() string {
	return string(e)
}

func (e *ModerationStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ModerationStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ModerationStatus", str)
	}
	return nil
}

func (e ModerationStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ModerationStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ModerationStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type OrgRole string

const (
	OrgRoleOwner   OrgRole = "OWNER"
	OrgRoleAdmin   OrgRole = "ADMIN"
	OrgRoleAnalyst OrgRole = "ANALYST"
	OrgRoleViewer  OrgRole = "VIEWER"
)

var AllOrgRole = []OrgRole{
	OrgRoleOwner,
	OrgRoleAdmin,
	OrgRoleAnalyst,
	OrgRoleViewer,
}

func (e OrgRole) IsValid() bool {
	switch e {
	case OrgRoleOwner, OrgRoleAdmin, OrgRoleAnalyst, OrgRoleViewer:
		return true
	}
	return false
}

func (e OrgRole) String() string {
	return string(e)
}

func (e *OrgRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrgRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrgRole", str)
	}
	return nil
}

func (e OrgRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrgRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrgRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type OrgType string

const (
	OrgTypePersonal     OrgType = "PERSONAL"
	OrgTypeOrganization OrgType = "ORGANIZATION"
)

var AllOrgType = []OrgType{
	OrgTypePersonal,
	OrgTypeOrganization,
}

func (e OrgType) IsValid() bool {
	switch e {
	case OrgTypePersonal, OrgTypeOrganization:
		return true
	}
	return false
}

func (e OrgType) String() string {
	return string(e)
}

func (e *OrgType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrgType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrgType", str)
	}
	return nil
}

func (e OrgType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrgType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrgType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PolicyStatus string

const (
	PolicyStatusDraft     PolicyStatus = "DRAFT"
	PolicyStatusPublished PolicyStatus = "PUBLISHED"
	PolicyStatusArchived  PolicyStatus = "ARCHIVED"
)

var AllPolicyStatus = []PolicyStatus{
	PolicyStatusDraft,
	PolicyStatusPublished,
	PolicyStatusArchived,
}

func (e PolicyStatus) IsValid() bool {
	switch e {
	case PolicyStatusDraft, PolicyStatusPublished, PolicyStatusArchived:
		return true
	}
	return false
}

func (e PolicyStatus) String() string {
	return string(e)
}

func (e *PolicyStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PolicyStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PolicyStatus", str)
	}
	return nil
}

func (e PolicyStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PolicyStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PolicyStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type QualityStatus string

const (
	QualityStatusPending    QualityStatus = "PENDING"
	QualityStatusApproved   QualityStatus = "APPROVED"
	QualityStatusLowQuality QualityStatus = "LOW_QUALITY"
	QualityStatusRejected   QualityStatus = "REJECTED"
)

var AllQualityStatus = []QualityStatus{
	QualityStatusPending,
	QualityStatusApproved,
	QualityStatusLowQuality,
	QualityStatusRejected,
}

func (e QualityStatus) IsValid() bool {
	switch e {
	case QualityStatusPending, QualityStatusApproved, QualityStatusLowQuality, QualityStatusRejected:
		return true
	}
	return false
}

func (e QualityStatus) String() string {
	return string(e)
}

func (e *QualityStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = QualityStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid QualityStatus", str)
	}
	return nil
}

func (e QualityStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *QualityStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e QualityStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SatisfactionLevel string

const (
	SatisfactionLevelVerySatisfied   SatisfactionLevel = "VERY_SATISFIED"
	SatisfactionLevelSatisfied       SatisfactionLevel = "SATISFIED"
	SatisfactionLevelNeutral         SatisfactionLevel = "NEUTRAL"
	SatisfactionLevelUnsatisfied     SatisfactionLevel = "UNSATISFIED"
	SatisfactionLevelVeryUnsatisfied SatisfactionLevel = "VERY_UNSATISFIED"
)

var AllSatisfactionLevel = []SatisfactionLevel{
	SatisfactionLevelVerySatisfied,
	SatisfactionLevelSatisfied,
	SatisfactionLevelNeutral,
	SatisfactionLevelUnsatisfied,
	SatisfactionLevelVeryUnsatisfied,
}

func (e SatisfactionLevel) IsValid() bool {
	switch e {
	case SatisfactionLevelVerySatisfied, SatisfactionLevelSatisfied, SatisfactionLevelNeutral, SatisfactionLevelUnsatisfied, SatisfactionLevelVeryUnsatisfied:
		return true
	}
	return false
}

func (e SatisfactionLevel) String() string {
	return string(e)
}

func (e *SatisfactionLevel) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SatisfactionLevel(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SatisfactionLevel", str)
	}
	return nil
}

func (e SatisfactionLevel) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SatisfactionLevel) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SatisfactionLevel) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UsageStatus string

const (
	UsageStatusUsing UsageStatus = "USING"
	UsageStatusUsed  UsageStatus = "USED"
)

var AllUsageStatus = []UsageStatus{
	UsageStatusUsing,
	UsageStatusUsed,
}

func (e UsageStatus) IsValid() bool {
	switch e {
	case UsageStatusUsing, UsageStatusUsed:
		return true
	}
	return false
}

func (e UsageStatus) String() string {
	return string(e)
}

func (e *UsageStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UsageStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UsageStatus", str)
	}
	return nil
}

func (e UsageStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UsageStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UsageStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
