package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"encoding/base64"
	"errors"
	"time"

	"github.com/Busenuryurdakul/cocuk-urun-analiz/apps/api/graph/model"
	"github.com/Busenuryurdakul/cocuk-urun-analiz/apps/api/internal/agent"
	"github.com/Busenuryurdakul/cocuk-urun-analiz/apps/api/internal/compliance"
	"github.com/Busenuryurdakul/cocuk-urun-analiz/apps/api/internal/cookies"
	"github.com/Busenuryurdakul/cocuk-urun-analiz/apps/api/internal/dataset"
	"github.com/Busenuryurdakul/cocuk-urun-analiz/apps/api/internal/domain"
	"github.com/Busenuryurdakul/cocuk-urun-analiz/apps/api/internal/httpx"
	"github.com/Busenuryurdakul/cocuk-urun-analiz/apps/api/internal/marketplace"
	"github.com/Busenuryurdakul/cocuk-urun-analiz/apps/api/internal/product"
	"github.com/Busenuryurdakul/cocuk-urun-analiz/apps/api/internal/rbac"
	"github.com/Busenuryurdakul/cocuk-urun-analiz/apps/api/internal/ugc"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.RegisterPayload, error) {
	result, err := r.Auth.Register(ctx, input.Email, input.Password)
	if err != nil {
		return nil, mapAuthError(err)
	}
	return &model.RegisterPayload{Message: result.Message}, nil
}

// VerifyEmail is the resolver for the verifyEmail field.
func (r *mutationResolver) VerifyEmail(ctx context.Context, token string) (*model.MFASetupPayload, error) {
	setup, err := r.Auth.VerifyEmail(ctx, token)
	if err != nil {
		return nil, mapAuthError(err)
	}
	applyMFASetupCookie(ctx, r.CookieOpts, setup)
	return &model.MFASetupPayload{
		Secret:     setup.Secret,
		OtpauthURL: setup.OTPAuthURL,
	}, nil
}

// ConfirmMfa is the resolver for the confirmMFA field.
func (r *mutationResolver) ConfirmMfa(ctx context.Context, input model.ConfirmMFAInput) (bool, error) {
	req, ok := httpx.RequestFrom(ctx)
	if !ok {
		return false, gqlError("INVALID_TOKEN", errUnauthorized)
	}
	setupToken, ok := cookies.Get(req, cookies.SetupCookie)
	if !ok {
		return false, gqlError("INVALID_TOKEN", errUnauthorized)
	}
	if err := r.Auth.ConfirmMFA(ctx, setupToken, input.Code); err != nil {
		return false, mapAuthError(err)
	}
	if w, ok := responseWriter(ctx); ok {
		cookies.Clear(w, cookies.SetupCookie, r.CookieOpts)
	}
	return true, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.LoginPayload, error) {
	result, err := r.Auth.Login(ctx, input.Email, input.Password, input.DeviceFingerprint)
	if err != nil {
		return nil, mapAuthError(err)
	}
	applyLoginCookies(ctx, r.CookieOpts, result)
	return toModelLoginPayload(result), nil
}

// VerifyLoginMfa is the resolver for the verifyLoginMFA field.
func (r *mutationResolver) VerifyLoginMfa(ctx context.Context, input model.VerifyLoginMFAInput) (*model.LoginPayload, error) {
	req, ok := httpx.RequestFrom(ctx)
	if !ok {
		return nil, gqlError("INVALID_TOKEN", errUnauthorized)
	}
	pendingToken, ok := cookies.Get(req, cookies.PendingCookie)
	if !ok {
		return nil, gqlError("INVALID_TOKEN", errUnauthorized)
	}
	result, err := r.Auth.VerifyLoginMFA(ctx, pendingToken, input.Code, input.DeviceFingerprint)
	if err != nil {
		return nil, mapAuthError(err)
	}
	applyLoginCookies(ctx, r.CookieOpts, result)
	return toModelLoginPayload(result), nil
}

// VerifyDevice is the resolver for the verifyDevice field.
func (r *mutationResolver) VerifyDevice(ctx context.Context, input model.VerifyDeviceInput) (*model.LoginPayload, error) {
	req, ok := httpx.RequestFrom(ctx)
	if !ok {
		return nil, gqlError("INVALID_TOKEN", errUnauthorized)
	}
	pendingToken, ok := cookies.Get(req, cookies.PendingCookie)
	if !ok {
		return nil, gqlError("INVALID_TOKEN", errUnauthorized)
	}
	result, err := r.Auth.VerifyDevice(ctx, pendingToken, input.Code, input.DeviceFingerprint)
	if err != nil {
		return nil, mapAuthError(err)
	}
	applyLoginCookies(ctx, r.CookieOpts, result)
	return toModelLoginPayload(result), nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	session, err := requireSession(ctx)
	if err == nil {
		if sid, parseErr := parseObjectID(session.SessionID); parseErr == nil {
			_ = r.Auth.LogoutSession(ctx, sid)
		}
	}
	clearAuthCookies(ctx, r.CookieOpts)
	return true, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context) (bool, error) {
	req, ok := httpx.RequestFrom(ctx)
	if !ok {
		return false, gqlError("UNAUTHORIZED", errUnauthorized)
	}
	refresh, ok := cookies.Get(req, cookies.RefreshCookie)
	if !ok {
		return false, gqlError("INVALID_TOKEN", errUnauthorized)
	}
	tokens, err := r.Auth.RefreshTokens(ctx, refresh)
	if err != nil {
		clearAuthCookies(ctx, r.CookieOpts)
		return false, mapAuthError(err)
	}
	applyAuthCookies(ctx, r.CookieOpts, tokens)
	return true, nil
}

// SwitchWorkspace is the resolver for the switchWorkspace field.
func (r *mutationResolver) SwitchWorkspace(ctx context.Context, organizationID string) (bool, error) {
	session, err := requireSession(ctx)
	if err != nil {
		return false, gqlError("UNAUTHORIZED", err)
	}
	orgID, err := parseObjectID(organizationID)
	if err != nil {
		return false, gqlError("INVALID_ID", err)
	}
	sessionID, err := parseObjectID(session.SessionID)
	if err != nil {
		return false, err
	}
	tokens, err := r.Auth.SwitchWorkspaceTokens(ctx, sessionID, orgID)
	if err != nil {
		return false, mapAuthError(err)
	}
	applyAuthCookies(ctx, r.CookieOpts, tokens)
	return true, nil
}

// CreateOrganization is the resolver for the createOrganization field.
func (r *mutationResolver) CreateOrganization(ctx context.Context, input model.CreateOrganizationInput) (*model.Organization, error) {
	actorID, err := requireActor(ctx)
	if err != nil {
		return nil, gqlError("UNAUTHORIZED", err)
	}
	org, err := r.Org.CreateOrganization(ctx, actorID, input.Name, string(input.ComplianceProfile))
	if err != nil {
		return nil, mapAuthError(err)
	}
	return toModelOrganization(org), nil
}

// InviteMember is the resolver for the inviteMember field.
func (r *mutationResolver) InviteMember(ctx context.Context, input model.InviteMemberInput) (bool, error) {
	actorID, err := requireActor(ctx)
	if err != nil {
		return false, gqlError("UNAUTHORIZED", err)
	}
	orgID, err := parseObjectID(input.OrganizationID)
	if err != nil {
		return false, gqlError("INVALID_ID", err)
	}
	if err := r.Org.InviteMember(ctx, actorID, orgID, input.Email, string(input.Role)); err != nil {
		return false, mapAuthError(err)
	}
	return true, nil
}

// AcceptInvitation is the resolver for the acceptInvitation field.
func (r *mutationResolver) AcceptInvitation(ctx context.Context, token string) (*model.Organization, error) {
	actorID, err := requireActor(ctx)
	if err != nil {
		return nil, gqlError("UNAUTHORIZED", err)
	}
	org, err := r.Org.AcceptInvitation(ctx, actorID, token)
	if err != nil {
		return nil, mapAuthError(err)
	}
	return toModelOrganization(org), nil
}

// UpdateMemberRole is the resolver for the updateMemberRole field.
func (r *mutationResolver) UpdateMemberRole(ctx context.Context, input model.UpdateMemberRoleInput) (bool, error) {
	actorID, err := requireActor(ctx)
	if err != nil {
		return false, gqlError("UNAUTHORIZED", err)
	}
	orgID, err := parseObjectID(input.OrganizationID)
	if err != nil {
		return false, gqlError("INVALID_ID", err)
	}
	targetID, err := parseObjectID(input.UserID)
	if err != nil {
		return false, gqlError("INVALID_ID", err)
	}
	if err := r.Org.UpdateMemberRole(ctx, actorID, orgID, targetID, string(input.Role)); err != nil {
		return false, mapAuthError(err)
	}
	return true, nil
}

// RemoveMember is the resolver for the removeMember field.
func (r *mutationResolver) RemoveMember(ctx context.Context, input model.RemoveMemberInput) (bool, error) {
	actorID, err := requireActor(ctx)
	if err != nil {
		return false, gqlError("UNAUTHORIZED", err)
	}
	orgID, err := parseObjectID(input.OrganizationID)
	if err != nil {
		return false, gqlError("INVALID_ID", err)
	}
	targetID, err := parseObjectID(input.UserID)
	if err != nil {
		return false, gqlError("INVALID_ID", err)
	}
	if err := r.Org.RemoveMember(ctx, actorID, orgID, targetID); err != nil {
		return false, mapAuthError(err)
	}
	return true, nil
}

// UpdateOrganizationComplianceProfile is the resolver for the updateOrganizationComplianceProfile field.
func (r *mutationResolver) UpdateOrganizationComplianceProfile(ctx context.Context, input model.UpdateComplianceProfileInput) (*model.Organization, error) {
	actorID, err := requireActor(ctx)
	if err != nil {
		return nil, gqlError("UNAUTHORIZED", err)
	}
	orgID, err := parseObjectID(input.OrganizationID)
	if err != nil {
		return nil, gqlError("INVALID_ID", err)
	}
	org, err := r.Org.UpdateComplianceProfile(ctx, actorID, orgID, string(input.ComplianceProfile))
	if err != nil {
		return nil, mapAuthError(err)
	}
	return toModelOrganization(org), nil
}

// PublishCompliancePolicyVersion is the resolver for the publishCompliancePolicyVersion field.
func (r *mutationResolver) PublishCompliancePolicyVersion(ctx context.Context, input model.PublishCompliancePolicyInput) (*model.CompliancePolicy, error) {
	actorID, err := requireActor(ctx)
	if err != nil {
		return nil, gqlError("UNAUTHORIZED", err)
	}
	orgID, err := parseObjectID(input.OrganizationID)
	if err != nil {
		return nil, gqlError("INVALID_ID", err)
	}
	policy, err := r.Org.PublishCompliancePolicy(ctx, actorID, orgID, string(input.ComplianceProfile), input.Version, input.Reason)
	if err != nil {
		return nil, mapAuthError(err)
	}
	return toModelCompliancePolicy(policy), nil
}

// GrantConsent is the resolver for the grantConsent field.
func (r *mutationResolver) GrantConsent(ctx context.Context, input model.GrantConsentInput) (*model.Consent, error) {
	actorID, err := requireActor(ctx)
	if err != nil {
		return nil, gqlError("UNAUTHORIZED", err)
	}

	var orgPtr *primitive.ObjectID
	policyVersion := "1.0.0"

	if input.OrganizationID != nil {
		parsed, parseErr := parseObjectID(*input.OrganizationID)
		if parseErr != nil {
			return nil, gqlError("INVALID_ID", parseErr)
		}
		orgPtr = &parsed
		role, tenantErr := r.Auth.Tenant.RequireMembership(ctx, actorID, parsed)
		if tenantErr != nil {
			return nil, mapAuthError(tenantErr)
		}
		if !rbac.CanReadWorkspace(role) {
			return nil, gqlError("FORBIDDEN", errForbidden)
		}
		org, orgErr := r.Auth.Orgs.FindByID(ctx, parsed)
		if orgErr != nil {
			return nil, mapAuthError(orgErr)
		}
		if active, polErr := r.PolicyRepo.ResolveActive(ctx, org); polErr == nil {
			policyVersion = active.Version
		}
	} else {
		user, userErr := r.Auth.Users.FindByID(ctx, actorID)
		if userErr != nil {
			return nil, mapAuthError(userErr)
		}
		org, orgErr := r.Auth.Orgs.FindByID(ctx, user.PersonalOrgID)
		if orgErr == nil {
			if active, polErr := r.PolicyRepo.ResolveActive(ctx, org); polErr == nil {
				policyVersion = active.Version
			}
		}
	}

	if _, err := r.Compliance.Evaluate(ctx, compliance.EvaluateRequest{
		Operation: "grant_consent",
		UserID:    actorID,
		Fields:    map[string]string{"purpose": string(input.Purpose)},
	}); err != nil {
		if errors.Is(err, compliance.ErrBypassAttempt) {
			return nil, mapAuthError(err)
		}
	}

	consent, err := r.Consent.Grant(ctx, actorID, orgPtr, domain.ConsentPurpose(input.Purpose), domain.ConsentSourceWeb, policyVersion)
	if err != nil {
		return nil, mapAuthError(err)
	}
	return toModelConsent(consent), nil
}

// WithdrawConsent is the resolver for the withdrawConsent field.
func (r *mutationResolver) WithdrawConsent(ctx context.Context, input model.WithdrawConsentInput) (bool, error) {
	actorID, err := requireActor(ctx)
	if err != nil {
		return false, gqlError("UNAUTHORIZED", err)
	}
	var orgPtr *primitive.ObjectID
	if input.OrganizationID != nil {
		parsed, parseErr := parseObjectID(*input.OrganizationID)
		if parseErr != nil {
			return false, gqlError("INVALID_ID", parseErr)
		}
		orgPtr = &parsed
		if _, tenantErr := r.Auth.Tenant.RequireMembership(ctx, actorID, parsed); tenantErr != nil {
			return false, mapAuthError(tenantErr)
		}
	}
	if err := r.Consent.Withdraw(ctx, actorID, orgPtr, domain.ConsentPurpose(input.Purpose)); err != nil {
		return false, mapAuthError(err)
	}
	return true, nil
}

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.CreateProductInput) (*model.CreateProductPayload, error) {
	actorID, err := requireActor(ctx)
	if err != nil {
		return nil, gqlError("UNAUTHORIZED", err)
	}
	orgID, err := parseObjectID(input.OrganizationID)
	if err != nil {
		return nil, gqlError("INVALID_ID", err)
	}
	productResult, dedup, err := r.ProductService.Create(ctx, product.CreateInput{
		OrganizationID:  orgID,
		ActorID:         actorID,
		Name:            input.Name,
		Brand:           deref(input.Brand),
		Category:        deref(input.Category),
		Description:     deref(input.Description),
		TargetAge:       deref(input.TargetAge),
		Materials:       deref(input.Materials),
		SafetyWarnings:  deref(input.SafetyWarnings),
		CurrentPrice:    deref(input.CurrentPrice),
		OriginalPrice:   deref(input.OriginalPrice),
		Currency:        deref(input.Currency),
		Seller:          deref(input.Seller),
		Rating:          deref(input.Rating),
		ReviewCount:     deref(input.ReviewCount),
		StockStatus:     deref(input.StockStatus),
		Source:          domain.MarketplaceSource(input.Source),
		SourceProductID: input.SourceProductID,
		SourceURL:       deref(input.SourceURL),
		SKU:             deref(input.Sku),
	})
	if err != nil {
		return nil, mapPhase4Error(err)
	}
	return &model.CreateProductPayload{
		Product:      toModelProduct(productResult),
		Deduplicated: dedup,
	}, nil
}

// CreateUserExperience is the resolver for the createUserExperience field.
func (r *mutationResolver) CreateUserExperience(ctx context.Context, input model.CreateUserExperienceInput) (*model.UserExperience, error) {
	actorID, err := requireActor(ctx)
	if err != nil {
		return nil, gqlError("UNAUTHORIZED", err)
	}
	orgID, productID, err := parseOrgProductIDs(input.OrganizationID, input.ProductID)
	if err != nil {
		return nil, gqlError("INVALID_ID", err)
	}
	ux, err := r.UGCService.Create(ctx, ugc.CreateInput{
		OrganizationID:    orgID,
		ActorID:           actorID,
		ProductID:         productID,
		UsageStatus:       domain.UsageStatus(input.UsageStatus),
		SatisfactionLevel: domain.SatisfactionLevel(input.SatisfactionLevel),
		Rating:            input.Rating,
		IssueType:         derefIssueType(input.IssueType),
		Narrative:         input.Narrative,
	})
	if err != nil {
		return nil, mapPhase4Error(err)
	}
	return toModelUserExperience(ux), nil
}

// UpdateUserExperience is the resolver for the updateUserExperience field.
func (r *mutationResolver) UpdateUserExperience(ctx context.Context, input model.UpdateUserExperienceInput) (*model.UserExperience, error) {
	actorID, err := requireActor(ctx)
	if err != nil {
		return nil, gqlError("UNAUTHORIZED", err)
	}
	orgID, err := parseObjectID(input.OrganizationID)
	if err != nil {
		return nil, gqlError("INVALID_ID", err)
	}
	expID, err := parseObjectID(input.ExperienceID)
	if err != nil {
		return nil, gqlError("INVALID_ID", err)
	}
	ux, err := r.UGCService.Update(ctx, ugc.UpdateInput{
		OrganizationID:    orgID,
		ActorID:           actorID,
		ExperienceID:      expID,
		UsageStatus:       domain.UsageStatus(input.UsageStatus),
		SatisfactionLevel: domain.SatisfactionLevel(input.SatisfactionLevel),
		Rating:            input.Rating,
		IssueType:         derefIssueType(input.IssueType),
		Narrative:         input.Narrative,
	})
	if err != nil {
		return nil, mapPhase4Error(err)
	}
	return toModelUserExperience(ux), nil
}

// DeleteUserExperience is the resolver for the deleteUserExperience field.
func (r *mutationResolver) DeleteUserExperience(ctx context.Context, input model.DeleteUserExperienceInput) (bool, error) {
	actorID, err := requireActor(ctx)
	if err != nil {
		return false, gqlError("UNAUTHORIZED", err)
	}
	orgID, err := parseObjectID(input.OrganizationID)
	if err != nil {
		return false, gqlError("INVALID_ID", err)
	}
	expID, err := parseObjectID(input.ExperienceID)
	if err != nil {
		return false, gqlError("INVALID_ID", err)
	}
	if err := r.UGCService.Delete(ctx, actorID, orgID, expID); err != nil {
		return false, mapPhase4Error(err)
	}
	return true, nil
}

// ModerateUserExperience is the resolver for the moderateUserExperience field.
func (r *mutationResolver) ModerateUserExperience(ctx context.Context, input model.ModerateUserExperienceInput) (*model.UserExperience, error) {
	actorID, err := requireActor(ctx)
	if err != nil {
		return nil, gqlError("UNAUTHORIZED", err)
	}
	orgID, err := parseObjectID(input.OrganizationID)
	if err != nil {
		return nil, gqlError("INVALID_ID", err)
	}
	expID, err := parseObjectID(input.ExperienceID)
	if err != nil {
		return nil, gqlError("INVALID_ID", err)
	}
	var quality *domain.QualityStatus
	if input.QualityStatus != nil {
		v := domain.QualityStatus(*input.QualityStatus)
		quality = &v
	}
	ux, err := r.UGCService.Moderate(ctx, ugc.ModerateInput{
		OrganizationID:   orgID,
		ActorID:          actorID,
		ExperienceID:     expID,
		ModerationStatus: domain.ModerationStatus(input.ModerationStatus),
		QualityStatus:    quality,
	})
	if err != nil {
		return nil, mapPhase4Error(err)
	}
	return toModelUserExperience(ux), nil
}

// StartMarketplaceURLImport is the resolver for the startMarketplaceURLImport field.
func (r *mutationResolver) StartMarketplaceURLImport(ctx context.Context, input model.StartMarketplaceURLImportInput) (*model.MarketplaceImportRun, error) {
	actorID, err := requireActor(ctx)
	if err != nil {
		return nil, gqlError("UNAUTHORIZED", err)
	}
	orgID, err := parseObjectID(input.OrganizationID)
	if err != nil {
		return nil, gqlError("INVALID_ID", err)
	}
	run, err := r.MarketplaceService.StartURLImport(ctx, marketplace.StartURLImportInput{
		OrganizationID: orgID,
		ActorID:        actorID,
		SourceURL:      input.SourceURL,
	})
	if err != nil {
		return nil, mapPhase4Error(err)
	}
	return toModelImportRun(run), nil
}

// StartMarketplaceFileImport is the resolver for the startMarketplaceFileImport field.
func (r *mutationResolver) StartMarketplaceFileImport(ctx context.Context, input model.StartMarketplaceFileImportInput) (*model.MarketplaceImportRun, error) {
	actorID, err := requireActor(ctx)
	if err != nil {
		return nil, gqlError("UNAUTHORIZED", err)
	}
	orgID, err := parseObjectID(input.OrganizationID)
	if err != nil {
		return nil, gqlError("INVALID_ID", err)
	}
	content, err := base64.StdEncoding.DecodeString(input.ContentBase64)
	if err != nil {
		return nil, gqlError("INVALID_INPUT", err)
	}
	run, err := r.MarketplaceService.StartFileImport(ctx, marketplace.StartFileImportInput{
		OrganizationID: orgID,
		ActorID:        actorID,
		Source:         domain.MarketplaceSource(input.Source),
		AccessMode:     domain.AccessMode(input.AccessMode),
		Filename:       input.Filename,
		Content:        content,
		ContentType:    input.ContentType,
	})
	if err != nil {
		return nil, mapPhase4Error(err)
	}
	return toModelImportRun(run), nil
}

// BuildDatasetDraft is the resolver for the buildDatasetDraft field.
func (r *mutationResolver) BuildDatasetDraft(ctx context.Context, input model.BuildDatasetDraftInput) (*model.DatasetVersion, error) {
	actorID, err := requireActor(ctx)
	if err != nil {
		return nil, gqlError("UNAUTHORIZED", err)
	}
	orgID, err := parseObjectID(input.OrganizationID)
	if err != nil {
		return nil, gqlError("INVALID_ID", err)
	}
	version, err := r.DatasetService.BuildDatasetDraft(ctx, dataset.BuildDraftInput{
		OrganizationID: orgID,
		ActorID:        actorID,
		VersionLabel:   input.Version,
	})
	if err != nil {
		return nil, mapPhase4Error(err)
	}
	return toModelDatasetVersion(version), nil
}

// StartAgentRun is the resolver for the startAgentRun field.
func (r *mutationResolver) StartAgentRun(ctx context.Context, input model.StartAgentRunInput) (*model.AnalysisRun, error) {
	actorID, err := requireActor(ctx)
	if err != nil {
		return nil, err
	}
	orgID, err := parseObjectID(input.OrganizationID)
	if err != nil {
		return nil, gqlError("INVALID_INPUT", err)
	}
	productID, err := parseObjectID(input.ProductID)
	if err != nil {
		return nil, gqlError("INVALID_INPUT", err)
	}
	startInput := agent.StartRunInput{
		OrganizationID:  orgID,
		ActorID:         actorID,
		ProductID:       productID,
		ClientRequestID: input.ClientRequestID,
	}
	if input.MarketplaceImportRunID != nil {
		importRunID, err := parseObjectID(*input.MarketplaceImportRunID)
		if err != nil {
			return nil, gqlError("INVALID_INPUT", err)
		}
		startInput.MarketplaceImportRunID = &importRunID
	}

	run, err := r.AgentService.StartRun(ctx, startInput)
	if err != nil {
		return nil, mapPhase5Error(err)
	}
	return toModelAnalysisRun(run), nil
}

// CancelAgentRun is the resolver for the cancelAgentRun field.
func (r *mutationResolver) CancelAgentRun(ctx context.Context, input model.CancelAgentRunInput) (*model.AnalysisRun, error) {
	actorID, err := requireActor(ctx)
	if err != nil {
		return nil, err
	}
	orgID, err := parseObjectID(input.OrganizationID)
	if err != nil {
		return nil, gqlError("INVALID_INPUT", err)
	}
	runID, err := parseObjectID(input.AnalysisRunID)
	if err != nil {
		return nil, gqlError("INVALID_INPUT", err)
	}
	run, err := r.AgentService.CancelRun(ctx, actorID, orgID, runID)
	if err != nil {
		return nil, mapPhase5Error(err)
	}
	return toModelAnalysisRun(run), nil
}

// Health returns GraphQL layer health.
func (r *queryResolver) Health(ctx context.Context) (string, error) {
	return "ok", nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	session, err := requireSession(ctx)
	if err != nil {
		return nil, gqlError("UNAUTHORIZED", err)
	}
	userID, err := parseObjectID(session.UserID)
	if err != nil {
		return nil, err
	}
	user, err := r.Auth.Users.FindByID(ctx, userID)
	if err != nil {
		return nil, mapAuthError(err)
	}
	return toModelUser(user), nil
}

// MyWorkspaces is the resolver for the myWorkspaces field.
func (r *queryResolver) MyWorkspaces(ctx context.Context) ([]*model.Workspace, error) {
	session, err := requireSession(ctx)
	if err != nil {
		return nil, gqlError("UNAUTHORIZED", err)
	}
	userID, err := parseObjectID(session.UserID)
	if err != nil {
		return nil, err
	}
	entries, err := r.Auth.ListWorkspaces(ctx, userID)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Workspace, 0, len(entries))
	for _, e := range entries {
		out = append(out, &model.Workspace{
			OrganizationID: e.Organization.ID.Hex(),
			Name:           e.Organization.Name,
			Type:           toModelOrgType(e.Organization.Type),
			Role:           toModelOrgRole(e.Role),
		})
	}
	return out, nil
}

// Organization is the resolver for the organization field.
func (r *queryResolver) Organization(ctx context.Context, organizationID string) (*model.Organization, error) {
	session, err := requireSession(ctx)
	if err != nil {
		return nil, gqlError("UNAUTHORIZED", err)
	}
	userID, err := parseObjectID(session.UserID)
	if err != nil {
		return nil, err
	}
	orgID, err := parseObjectID(organizationID)
	if err != nil {
		return nil, gqlError("INVALID_ID", err)
	}
	org, _, err := r.Auth.GetOrganization(ctx, userID, orgID)
	if err != nil {
		return nil, mapAuthError(err)
	}
	return toModelOrganization(org), nil
}

// OrganizationMembers is the resolver for the organizationMembers field.
func (r *queryResolver) OrganizationMembers(ctx context.Context, organizationID string) ([]*model.OrganizationMember, error) {
	actorID, err := requireActor(ctx)
	if err != nil {
		return nil, gqlError("UNAUTHORIZED", err)
	}
	orgID, err := parseObjectID(organizationID)
	if err != nil {
		return nil, gqlError("INVALID_ID", err)
	}
	members, err := r.Org.ListMembers(ctx, actorID, orgID)
	if err != nil {
		return nil, mapAuthError(err)
	}
	out := make([]*model.OrganizationMember, 0, len(members))
	for _, m := range members {
		out = append(out, &model.OrganizationMember{
			UserID:    m.UserID.Hex(),
			Email:     m.Email,
			Role:      model.OrgRole(m.Role),
			JoinedAt:  m.JoinedAt.UTC().Format(time.RFC3339),
			InvitedAt: m.InvitedAt.UTC().Format(time.RFC3339),
		})
	}
	return out, nil
}

// ActiveCompliancePolicy is the resolver for the activeCompliancePolicy field.
func (r *queryResolver) ActiveCompliancePolicy(ctx context.Context, organizationID string) (*model.CompliancePolicy, error) {
	actorID, err := requireActor(ctx)
	if err != nil {
		return nil, gqlError("UNAUTHORIZED", err)
	}
	orgID, err := parseObjectID(organizationID)
	if err != nil {
		return nil, gqlError("INVALID_ID", err)
	}
	org, _, err := r.Auth.GetOrganization(ctx, actorID, orgID)
	if err != nil {
		return nil, mapAuthError(err)
	}
	policy, err := r.PolicyRepo.ResolveActive(ctx, org)
	if err != nil {
		return nil, mapAuthError(err)
	}
	return toModelCompliancePolicy(policy), nil
}

// CompliancePolicyVersions is the resolver for the compliancePolicyVersions field.
func (r *queryResolver) CompliancePolicyVersions(ctx context.Context, organizationID string, limit *int) ([]*model.CompliancePolicy, error) {
	actorID, err := requireActor(ctx)
	if err != nil {
		return nil, gqlError("UNAUTHORIZED", err)
	}
	orgID, err := parseObjectID(organizationID)
	if err != nil {
		return nil, gqlError("INVALID_ID", err)
	}
	role, err := r.Auth.Tenant.RequireMembership(ctx, actorID, orgID)
	if err != nil {
		return nil, mapAuthError(err)
	}
	if !rbac.CanUpdateCompliance(role) {
		return nil, gqlError("FORBIDDEN", errForbidden)
	}
	lim := int64(20)
	if limit != nil {
		lim = int64(*limit)
	}
	policies, err := r.PolicyRepo.Policies.ListPublishedByOrg(ctx, &orgID, lim)
	if err != nil {
		return nil, err
	}
	out := make([]*model.CompliancePolicy, 0, len(policies))
	for i := range policies {
		out = append(out, toModelCompliancePolicy(&policies[i]))
	}
	return out, nil
}

// MyConsents is the resolver for the myConsents field.
func (r *queryResolver) MyConsents(ctx context.Context) ([]*model.Consent, error) {
	actorID, err := requireActor(ctx)
	if err != nil {
		return nil, gqlError("UNAUTHORIZED", err)
	}
	consents, err := r.Consent.ListForUser(ctx, actorID)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Consent, 0, len(consents))
	for i := range consents {
		out = append(out, toModelConsent(&consents[i]))
	}
	return out, nil
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context, organizationID string, limit *int) ([]*model.Product, error) {
	actorID, err := requireActor(ctx)
	if err != nil {
		return nil, gqlError("UNAUTHORIZED", err)
	}
	orgID, err := parseObjectID(organizationID)
	if err != nil {
		return nil, gqlError("INVALID_ID", err)
	}
	items, err := r.ProductService.List(ctx, actorID, orgID, limitOrDefault(limit, 50))
	if err != nil {
		return nil, mapPhase4Error(err)
	}
	out := make([]*model.Product, 0, len(items))
	for i := range items {
		out = append(out, toModelProduct(&items[i]))
	}
	return out, nil
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, organizationID string, productID string) (*model.Product, error) {
	actorID, err := requireActor(ctx)
	if err != nil {
		return nil, gqlError("UNAUTHORIZED", err)
	}
	orgID, pid, err := parseOrgProductIDs(organizationID, productID)
	if err != nil {
		return nil, gqlError("INVALID_ID", err)
	}
	item, err := r.ProductService.Get(ctx, actorID, orgID, pid)
	if err != nil {
		return nil, mapPhase4Error(err)
	}
	return toModelProduct(item), nil
}

// UserExperiences is the resolver for the userExperiences field.
func (r *queryResolver) UserExperiences(ctx context.Context, organizationID string, productID string) ([]*model.UserExperience, error) {
	actorID, err := requireActor(ctx)
	if err != nil {
		return nil, gqlError("UNAUTHORIZED", err)
	}
	orgID, pid, err := parseOrgProductIDs(organizationID, productID)
	if err != nil {
		return nil, gqlError("INVALID_ID", err)
	}
	items, err := r.UGCService.ListByProduct(ctx, actorID, orgID, pid)
	if err != nil {
		return nil, mapPhase4Error(err)
	}
	out := make([]*model.UserExperience, 0, len(items))
	for i := range items {
		out = append(out, toModelUserExperience(&items[i]))
	}
	return out, nil
}

// MarketplaceImportRuns is the resolver for the marketplaceImportRuns field.
func (r *queryResolver) MarketplaceImportRuns(ctx context.Context, organizationID string, limit *int) ([]*model.MarketplaceImportRun, error) {
	actorID, err := requireActor(ctx)
	if err != nil {
		return nil, gqlError("UNAUTHORIZED", err)
	}
	orgID, err := parseObjectID(organizationID)
	if err != nil {
		return nil, gqlError("INVALID_ID", err)
	}
	runs, err := r.MarketplaceService.ListRuns(ctx, actorID, orgID, limitOrDefault(limit, 20))
	if err != nil {
		return nil, mapPhase4Error(err)
	}
	out := make([]*model.MarketplaceImportRun, 0, len(runs))
	for i := range runs {
		out = append(out, toModelImportRun(&runs[i]))
	}
	return out, nil
}

// DatasetVersions is the resolver for the datasetVersions field.
func (r *queryResolver) DatasetVersions(ctx context.Context, organizationID string, limit *int) ([]*model.DatasetVersion, error) {
	actorID, err := requireActor(ctx)
	if err != nil {
		return nil, gqlError("UNAUTHORIZED", err)
	}
	orgID, err := parseObjectID(organizationID)
	if err != nil {
		return nil, gqlError("INVALID_ID", err)
	}
	versions, err := r.DatasetService.ListVersions(ctx, actorID, orgID, limitOrDefault(limit, 20))
	if err != nil {
		return nil, mapPhase4Error(err)
	}
	out := make([]*model.DatasetVersion, 0, len(versions))
	for i := range versions {
		out = append(out, toModelDatasetVersion(&versions[i]))
	}
	return out, nil
}

// ProductMarketplaceReviews is the resolver for the productMarketplaceReviews field.
func (r *queryResolver) ProductMarketplaceReviews(ctx context.Context, organizationID string, productID string) ([]*model.MarketplaceReview, error) {
	actorID, err := requireActor(ctx)
	if err != nil {
		return nil, gqlError("UNAUTHORIZED", err)
	}
	orgID, pid, err := parseOrgProductIDs(organizationID, productID)
	if err != nil {
		return nil, gqlError("INVALID_ID", err)
	}
	items, err := r.MarketplaceService.ListReviewsByProduct(ctx, actorID, orgID, pid)
	if err != nil {
		return nil, mapPhase4Error(err)
	}
	out := make([]*model.MarketplaceReview, 0, len(items))
	for i := range items {
		out = append(out, toModelMarketplaceReview(&items[i]))
	}
	return out, nil
}

// MarketplaceImportStatus is the resolver for the marketplaceImportStatus field.
func (r *queryResolver) MarketplaceImportStatus(ctx context.Context, organizationID string, importRunID string) (*model.MarketplaceImportRun, error) {
	actorID, err := requireActor(ctx)
	if err != nil {
		return nil, gqlError("UNAUTHORIZED", err)
	}
	orgID, err := parseObjectID(organizationID)
	if err != nil {
		return nil, gqlError("INVALID_ID", err)
	}
	runID, err := parseObjectID(importRunID)
	if err != nil {
		return nil, gqlError("INVALID_ID", err)
	}
	run, err := r.MarketplaceService.GetRun(ctx, actorID, orgID, runID)
	if err != nil {
		return nil, mapPhase4Error(err)
	}
	return toModelImportRun(run), nil
}

// DatasetEligibilitySummary is the resolver for the datasetEligibilitySummary field.
func (r *queryResolver) DatasetEligibilitySummary(ctx context.Context, organizationID string) (*model.DatasetEligibilitySummary, error) {
	actorID, err := requireActor(ctx)
	if err != nil {
		return nil, gqlError("UNAUTHORIZED", err)
	}
	orgID, err := parseObjectID(organizationID)
	if err != nil {
		return nil, gqlError("INVALID_ID", err)
	}
	summary, err := r.DatasetService.EligibilitySummary(ctx, actorID, orgID)
	if err != nil {
		return nil, mapPhase4Error(err)
	}
	return toModelEligibilitySummary(summary), nil
}

// AgentRun is the resolver for the agentRun field.
func (r *queryResolver) AgentRun(ctx context.Context, organizationID string, analysisRunID string) (*model.AnalysisRun, error) {
	actorID, err := requireActor(ctx)
	if err != nil {
		return nil, err
	}
	orgID, err := parseObjectID(organizationID)
	if err != nil {
		return nil, gqlError("INVALID_INPUT", err)
	}
	runID, err := parseObjectID(analysisRunID)
	if err != nil {
		return nil, gqlError("INVALID_INPUT", err)
	}
	run, err := r.AgentService.GetRun(ctx, actorID, orgID, runID)
	if err != nil {
		return nil, mapPhase5Error(err)
	}
	return toModelAnalysisRun(run), nil
}

// AnalysisRuns is the resolver for the analysisRuns field.
func (r *queryResolver) AnalysisRuns(ctx context.Context, organizationID string, status *model.AnalysisRunStatus, limit *int) ([]*model.AnalysisRun, error) {
	actorID, err := requireActor(ctx)
	if err != nil {
		return nil, err
	}
	orgID, err := parseObjectID(organizationID)
	if err != nil {
		return nil, gqlError("INVALID_INPUT", err)
	}
	lim := 20
	if limit != nil {
		lim = *limit
	}

	runs, err := r.AgentService.ListRuns(ctx, actorID, orgID, domainAnalysisStatus(status), lim)
	if err != nil {
		return nil, mapPhase5Error(err)
	}
	out := make([]*model.AnalysisRun, 0, len(runs))
	for i := range runs {
		out = append(out, toModelAnalysisRun(&runs[i]))
	}
	return out, nil
}

// AgentRunEvents is the resolver for the agentRunEvents field.
func (r *queryResolver) AgentRunEvents(ctx context.Context, organizationID string, analysisRunID string, afterSequence *int, limit *int) ([]*model.AgentRunEvent, error) {
	actorID, err := requireActor(ctx)
	if err != nil {
		return nil, err
	}
	orgID, err := parseObjectID(organizationID)
	if err != nil {
		return nil, gqlError("INVALID_INPUT", err)
	}
	runID, err := parseObjectID(analysisRunID)
	if err != nil {
		return nil, gqlError("INVALID_INPUT", err)
	}
	after := int64(0)
	if afterSequence != nil {
		after = int64(*afterSequence)
	}
	lim := 100
	if limit != nil {
		lim = *limit
	}

	events, err := r.AgentService.ListEvents(ctx, actorID, orgID, runID, after, lim)
	if err != nil {
		return nil, mapPhase5Error(err)
	}
	return toModelAgentRunEvents(events), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
