import type { Locale } from "@/lib/i18n/locale-config";

type PhaseTable = Partial<Record<Locale, Record<string, string>>> & { en: Record<string, string>; tr: Record<string, string> };

const base = {
  LLM_REQUESTED: "Model request",
  LLM_COMPLETED: "Model response",
  LLM_FAILED: "Model error",
  LLM_FALLBACK_USED: "Switched to fallback model",
  LLM_ESCALATED: "Escalated to heavy model",
  RUN_STARTED: "Analysis started",
  RUN_COMPLETED: "Analysis completed",
  RUN_FAILED: "Analysis failed",
  RUN_CANCELLED: "Analysis cancelled",
  COMPLIANCE_PRECHECK: "Compliance check",
  TOOL_SELECTED: "Tool selected",
  TOOL_EXECUTION_STARTED: "Tool running",
  TOOL_EXECUTION_COMPLETED: "Tool completed",
  TOOL_REQUESTED: "Tool request",
  TOOL_COMPLETED: "Tool completed",
  TOOL_FAILED: "Tool error",
  OBSERVATION_CREATED: "Observation recorded",
  PLAN_CREATED: "Plan created",
};

export const PHASE_LABELS: PhaseTable = {
  tr: {
    LLM_REQUESTED: "Model isteği", LLM_COMPLETED: "Model yanıtı", LLM_FAILED: "Model hatası",
    LLM_FALLBACK_USED: "Yedek modele geçildi", LLM_ESCALATED: "Ağır modele yükseltildi",
    RUN_STARTED: "Analiz başladı", RUN_COMPLETED: "Analiz tamamlandı", RUN_FAILED: "Analiz başarısız",
    RUN_CANCELLED: "Analiz iptal edildi", COMPLIANCE_PRECHECK: "Uyumluluk kontrolü",
    TOOL_SELECTED: "Araç seçildi", TOOL_EXECUTION_STARTED: "Araç çalışıyor", TOOL_EXECUTION_COMPLETED: "Araç tamamlandı",
    TOOL_REQUESTED: "Araç isteği", TOOL_COMPLETED: "Araç tamamlandı", TOOL_FAILED: "Araç hatası",
    OBSERVATION_CREATED: "Gözlem kaydı", PLAN_CREATED: "Plan oluşturuldu",
  },
  en: base,
  de: {
    ...base,
    LLM_REQUESTED: "Modellanfrage", LLM_COMPLETED: "Modellantwort", LLM_FAILED: "Modellfehler",
    LLM_FALLBACK_USED: "Wechsel zum Ersatzmodell", LLM_ESCALATED: "Eskalation zum schweren Modell",
    RUN_STARTED: "Analyse gestartet", RUN_COMPLETED: "Analyse abgeschlossen", RUN_FAILED: "Analyse fehlgeschlagen",
    RUN_CANCELLED: "Analyse abgebrochen", COMPLIANCE_PRECHECK: "Compliance-Prüfung",
    TOOL_SELECTED: "Tool ausgewählt", TOOL_EXECUTION_STARTED: "Tool läuft", TOOL_EXECUTION_COMPLETED: "Tool abgeschlossen",
    TOOL_REQUESTED: "Tool-Anfrage", TOOL_COMPLETED: "Tool abgeschlossen", TOOL_FAILED: "Tool-Fehler",
    OBSERVATION_CREATED: "Beobachtung erfasst", PLAN_CREATED: "Plan erstellt",
  },
  fr: {
    ...base,
    LLM_REQUESTED: "Requête modèle", LLM_COMPLETED: "Réponse modèle", LLM_FAILED: "Erreur modèle",
    LLM_FALLBACK_USED: "Passage au modèle de secours", LLM_ESCALATED: "Escalade vers modèle lourd",
    RUN_STARTED: "Analyse démarrée", RUN_COMPLETED: "Analyse terminée", RUN_FAILED: "Analyse échouée",
    RUN_CANCELLED: "Analyse annulée", COMPLIANCE_PRECHECK: "Contrôle conformité",
    TOOL_SELECTED: "Outil sélectionné", TOOL_EXECUTION_STARTED: "Outil en cours", TOOL_EXECUTION_COMPLETED: "Outil terminé",
    TOOL_REQUESTED: "Requête outil", TOOL_COMPLETED: "Outil terminé", TOOL_FAILED: "Erreur outil",
    OBSERVATION_CREATED: "Observation enregistrée", PLAN_CREATED: "Plan créé",
  },
  es: {
    ...base,
    LLM_REQUESTED: "Solicitud de modelo", LLM_COMPLETED: "Respuesta del modelo", LLM_FAILED: "Error del modelo",
    LLM_FALLBACK_USED: "Cambio a modelo de respaldo", LLM_ESCALATED: "Escalado a modelo pesado",
    RUN_STARTED: "Análisis iniciado", RUN_COMPLETED: "Análisis completado", RUN_FAILED: "Análisis fallido",
    RUN_CANCELLED: "Análisis cancelado", COMPLIANCE_PRECHECK: "Control de cumplimiento",
    TOOL_SELECTED: "Herramienta seleccionada", TOOL_EXECUTION_STARTED: "Herramienta en ejecución",
    TOOL_EXECUTION_COMPLETED: "Herramienta completada", TOOL_REQUESTED: "Solicitud de herramienta",
    TOOL_COMPLETED: "Herramienta completada", TOOL_FAILED: "Error de herramienta",
    OBSERVATION_CREATED: "Observación registrada", PLAN_CREATED: "Plan creado",
  },
  ar: {
    ...base,
    LLM_REQUESTED: "طلب النموذج", LLM_COMPLETED: "استجابة النموذج", LLM_FAILED: "خطأ النموذج",
    LLM_FALLBACK_USED: "التحويل إلى النموذج الاحتياطي", LLM_ESCALATED: "تصعيد إلى النموذج الثقيل",
    RUN_STARTED: "بدأ التحليل", RUN_COMPLETED: "اكتمل التحليل", RUN_FAILED: "فشل التحليل",
    RUN_CANCELLED: "أُلغي التحليل", COMPLIANCE_PRECHECK: "فحص الامتثال",
    TOOL_SELECTED: "تم اختيار الأداة", TOOL_EXECUTION_STARTED: "الأداة تعمل", TOOL_EXECUTION_COMPLETED: "اكتملت الأداة",
    TOOL_REQUESTED: "طلب أداة", TOOL_COMPLETED: "اكتملت الأداة", TOOL_FAILED: "خطأ في الأداة",
    OBSERVATION_CREATED: "سُجلت الملاحظة", PLAN_CREATED: "تم إنشاء الخطة",
  },
  zh: {
    ...base,
    LLM_REQUESTED: "模型请求", LLM_COMPLETED: "模型响应", LLM_FAILED: "模型错误",
    LLM_FALLBACK_USED: "切换到备用模型", LLM_ESCALATED: "升级到重型模型",
    RUN_STARTED: "分析已开始", RUN_COMPLETED: "分析已完成", RUN_FAILED: "分析失败",
    RUN_CANCELLED: "分析已取消", COMPLIANCE_PRECHECK: "合规检查",
    TOOL_SELECTED: "已选工具", TOOL_EXECUTION_STARTED: "工具运行中", TOOL_EXECUTION_COMPLETED: "工具已完成",
    TOOL_REQUESTED: "工具请求", TOOL_COMPLETED: "工具已完成", TOOL_FAILED: "工具错误",
    OBSERVATION_CREATED: "已记录观察", PLAN_CREATED: "计划已创建",
  },
  ja: {
    ...base,
    LLM_REQUESTED: "モデル要求", LLM_COMPLETED: "モデル応答", LLM_FAILED: "モデルエラー",
    LLM_FALLBACK_USED: "フォールバックモデルへ切替", LLM_ESCALATED: "大型モデルへ昇格",
    RUN_STARTED: "分析開始", RUN_COMPLETED: "分析完了", RUN_FAILED: "分析失敗",
    RUN_CANCELLED: "分析キャンセル", COMPLIANCE_PRECHECK: "コンプライアンス確認",
    TOOL_SELECTED: "ツール選択", TOOL_EXECUTION_STARTED: "ツール実行中", TOOL_EXECUTION_COMPLETED: "ツール完了",
    TOOL_REQUESTED: "ツール要求", TOOL_COMPLETED: "ツール完了", TOOL_FAILED: "ツールエラー",
    OBSERVATION_CREATED: "観測記録", PLAN_CREATED: "プラン作成",
  },
  ru: {
    ...base,
    LLM_REQUESTED: "Запрос модели", LLM_COMPLETED: "Ответ модели", LLM_FAILED: "Ошибка модели",
    LLM_FALLBACK_USED: "Переход на резервную модель", LLM_ESCALATED: "Эскалация на тяжёлую модель",
    RUN_STARTED: "Анализ начат", RUN_COMPLETED: "Анализ завершён", RUN_FAILED: "Анализ не удался",
    RUN_CANCELLED: "Анализ отменён", COMPLIANCE_PRECHECK: "Проверка соответствия",
    TOOL_SELECTED: "Инструмент выбран", TOOL_EXECUTION_STARTED: "Инструмент выполняется",
    TOOL_EXECUTION_COMPLETED: "Инструмент завершён", TOOL_REQUESTED: "Запрос инструмента",
    TOOL_COMPLETED: "Инструмент завершён", TOOL_FAILED: "Ошибка инструмента",
    OBSERVATION_CREATED: "Наблюдение записано", PLAN_CREATED: "План создан",
  },
  pt: {
    ...base,
    LLM_REQUESTED: "Solicitação de modelo", LLM_COMPLETED: "Resposta do modelo", LLM_FAILED: "Erro do modelo",
    LLM_FALLBACK_USED: "Mudou para modelo de fallback", LLM_ESCALATED: "Escalado para modelo pesado",
    RUN_STARTED: "Análise iniciada", RUN_COMPLETED: "Análise concluída", RUN_FAILED: "Análise falhou",
    RUN_CANCELLED: "Análise cancelada", COMPLIANCE_PRECHECK: "Verificação de conformidade",
    TOOL_SELECTED: "Ferramenta selecionada", TOOL_EXECUTION_STARTED: "Ferramenta em execução",
    TOOL_EXECUTION_COMPLETED: "Ferramenta concluída", TOOL_REQUESTED: "Solicitação de ferramenta",
    TOOL_COMPLETED: "Ferramenta concluída", TOOL_FAILED: "Erro da ferramenta",
    OBSERVATION_CREATED: "Observação registrada", PLAN_CREATED: "Plano criado",
  },
};
