import type { Locale } from "@/lib/i18n/locale-config";

export type PolicyPhrase = Partial<Record<Locale, string>> & { en: string; tr: string };

export const POLICY_PHRASES: PolicyPhrase[] = [
  {
    en: "Risk signals exist but the match or evidence is not strong enough to block automatically.",
    tr: "Risk işaretleri var ancak eşleşme veya kanıt, otomatik engelleme için yeterince güçlü değil.",
    de: "Es gibt Risikosignale, aber Übereinstimmung oder Beweise reichen nicht für eine automatische Sperre.",
    fr: "Des signaux de risque existent, mais la correspondance ou les preuves ne suffisent pas pour bloquer automatiquement.",
    es: "Hay señales de riesgo, pero la coincidencia o la evidencia no son suficientes para bloquear automáticamente.",
    ar: "توجد مؤشرات مخاطر لكن التطابق أو الدليل غير كافٍ للحظر التلقائي.",
    zh: "存在风险信号，但匹配或证据不足以自动阻止。",
    ja: "リスク信号はありますが、一致または証拠が自動ブロックには不十分です。",
    ru: "Есть сигналы риска, но совпадение или доказательства недостаточны для автоматической блокировки.",
    pt: "Há sinais de risco, mas a correspondência ou evidência não é forte o suficiente para bloquear automaticamente.",
  },
  {
    en: "Official confirmed recall matched this product. Do not treat it as safe.",
    tr: "Resmi ve doğrulanmış bir geri çağırma bu ürünle eşleşti. Güvenli kabul etmeyin.",
    de: "Ein offiziell bestätigter Rückruf passt zu diesem Produkt. Nicht als sicher betrachten.",
    fr: "Un rappel officiel confirmé correspond à ce produit. Ne le considérez pas sûr.",
    es: "Un retiro oficial confirmado coincide con este producto. No lo considere seguro.",
    ar: "تطابق استدعاء رسمي مؤكد مع هذا المنتج. لا تعتبره آمناً.",
    zh: "官方确认的召回与该产品匹配。请勿视为安全。",
    ja: "公式確認済みリコールがこの製品と一致しました。安全と見なさないでください。",
    ru: "Официальный подтверждённый отзыв совпал с этим продуктом. Не считайте его безопасным.",
    pt: "Um recall oficial confirmado corresponde a este produto. Não o trate como seguro.",
  },
  {
    en: "High-severity finding is backed by strong persisted evidence.",
    tr: "Yüksek şiddetli bir bulgu güçlü kanıtla destekleniyor.",
    de: "Ein schwerwiegendes Ergebnis wird durch starke gespeicherte Beweise gestützt.",
    fr: "Une constatation grave est étayée par des preuves solides persistées.",
    es: "Un hallazgo de alta gravedad está respaldado por evidencia sólida persistida.",
    ar: "نتيجة عالية الخطورة مدعومة بأدلة قوية محفوظة.",
    zh: "高严重度发现由强有力的持久证据支持。",
    ja: "高深刻度の所見は強力な保存証拠に裏付けられています。",
    ru: "Вывод высокой серьёзности подкреплён сильными сохранёнными доказательствами.",
    pt: "Achado de alta gravidade é respaldado por evidência persistida forte.",
  },
  {
    en: "Sources disagree. A human reviewer should inspect the evidence.",
    tr: "Kaynaklar birbiriyle çelişiyor. Bir incelemenin kanıtı kontrol etmesi gerekir.",
    de: "Quellen widersprechen sich. Ein Prüfer sollte die Beweise untersuchen.",
    fr: "Les sources divergent. Un relecteur humain doit inspecter les preuves.",
    es: "Las fuentes no coinciden. Un revisor humano debe inspeccionar la evidencia.",
    ar: "المصادر متعارضة. يجب على مراجع بشري فحص الأدلة.",
    zh: "来源不一致。应由人工审核员检查证据。",
    ja: "ソースが一致しません。人間のレビュアーが証拠を確認する必要があります。",
    ru: "Источники расходятся. Человеку следует проверить доказательства.",
    pt: "As fontes discordam. Um revisor humano deve inspecionar a evidência.",
  },
  {
    en: "Supported medium-severity issues were found. Proceed with the listed warnings.",
    tr: "Desteklenen orta düzey sorunlar bulundu. Listelenen uyarılara dikkat edin.",
    de: "Unterstützte Probleme mittlerer Schwere wurden gefunden. Beachten Sie die Warnungen.",
    fr: "Des problèmes de gravité moyenne supportés ont été trouvés. Suivez les avertissements listés.",
    es: "Se encontraron problemas de gravedad media respaldados. Proceda con las advertencias listadas.",
    ar: "وُجدت مشكلات متوسطة الخطورة مدعومة. تابع مع التحذيرات المدرجة.",
    zh: "发现已支持的中等严重度问题。请遵循列出的警告。",
    ja: "支持された中程度の問題が見つかりました。リストされた警告に従ってください。",
    ru: "Найдены поддерживаемые проблемы средней серьёзности. Следуйте перечисленным предупреждениям.",
    pt: "Foram encontrados problemas de gravidade média suportados. Siga os avisos listados.",
  },
  {
    en: "Organization policy requires extra review when any safety finding is present.",
    tr: "Kuruluş politikası, herhangi bir güvenlik bulgusu olduğunda ek inceleme istiyor.",
    de: "Organisationsrichtlinie verlangt zusätzliche Prüfung bei Sicherheitsbefunden.",
    fr: "La politique de l'organisation exige un examen supplémentaire en cas de constat de sécurité.",
    es: "La política de la organización requiere revisión extra si hay hallazgos de seguridad.",
    ar: "سياسة المؤسسة تتطلب مراجعة إضافية عند وجود أي نتيجة سلامة.",
    zh: "组织政策要求在任何安全发现时进行额外审核。",
    ja: "組織ポリシーは安全上の所見がある場合に追加レビューを要求します。",
    ru: "Политика организации требует дополнительной проверки при любом выводе по безопасности.",
    pt: "A política da organização exige revisão extra quando há achado de segurança.",
  },
  {
    en: "No significant supported safety risk was confirmed.",
    tr: "Desteklenen önemli bir güvenlik riski doğrulanmadı.",
    de: "Kein signifikanter unterstützter Sicherheitsrisiko bestätigt.",
    fr: "Aucun risque de sécurité significatif supporté n'a été confirmé.",
    es: "No se confirmó un riesgo de seguridad significativo respaldado.",
    ar: "لم يُؤكد خطر سلامة مهم مدعوم.",
    zh: "未确认显著的支持性安全风险。",
    ja: "重要な支持された安全リスクは確認されませんでした。",
    ru: "Значительный поддерживаемый риск безопасности не подтверждён.",
    pt: "Nenhum risco de segurança significativo suportado foi confirmado.",
  },
  {
    en: "No approved reviews were available.",
    tr: "Onaylanmış kullanıcı yorumu bulunamadı.",
    de: "Keine genehmigten Nutzerbewertungen verfügbar.",
    fr: "Aucun avis utilisateur approuvé disponible.",
    es: "No había reseñas de usuario aprobadas.",
    ar: "لا توجد مراجعات مستخدم معتمدة.",
    zh: "没有可用的已批准用户评论。",
    ja: "承認されたユーザー review はありませんでした。",
    ru: "Нет одобренных отзывов пользователей.",
    pt: "Nenhuma avaliação de usuário aprovada disponível.",
  },
  {
    en: "Unverified recall language was removed from the confirmed recall list.",
    tr: "Doğrulanmamış geri çağırma ifadeleri onaylı listeden çıkarıldı.",
    de: "Unbestätigte Rückrufformulierungen wurden aus der bestätigten Liste entfernt.",
    fr: "Le langage de rappel non vérifié a été retiré de la liste confirmée.",
    es: "Se eliminó lenguaje de retiro no verificado de la lista confirmada.",
    ar: "أُزيلت عبارات الاستدعاء غير الم verified من القائمة المعتمدة.",
    zh: "未验证的召回表述已从确认列表中移除。",
    ja: "未検証のリコール表現は確認リストから削除されました。",
    ru: "Непроверенные формулировки об отзыве удалены из подтверждённого списка.",
    pt: "Linguagem de recall não verificada foi removida da lista confirmada.",
  },
  {
    en: "Weak or fuzzy recall match was not treated as confirmed.",
    tr: "Zayıf veya bulanık geri çağırma eşleşmesi doğrulanmış kabul edilmedi.",
    de: "Schwache oder unscharfe Rückrufübereinstimmung wurde nicht als bestätigt behandelt.",
    fr: "Une correspondance de rappel faible ou floue n'a pas été traitée comme confirmée.",
    es: "Una coincidencia de retiro débil o difusa no se trató como confirmada.",
    ar: "لم تُعامل مطابقة الاستدعاء الضعيفة أو الغامضة كمؤكدة.",
    zh: "弱或模糊的召回匹配未视为已确认。",
    ja: "弱いまたは曖昧なリコール一致は確認済みとして扱われませんでした。",
    ru: "Слабое или нечёткое совпадение отзыва не считалось подтверждённым.",
    pt: "Correspondência de recall fraca ou imprecisa não foi tratada como confirmada.",
  },
  {
    en: "Model mentioned a recall that is not backed by an official confirmed match.",
    tr: "Model, resmi doğrulanmış eşleşmeyle desteklenmeyen bir geri çağırma belirtti.",
    de: "Das Modell erwähnte einen Rückruf ohne offizielle bestätigte Übereinstimmung.",
    fr: "Le modèle a mentionné un rappel non étayé par une correspondance officielle confirmée.",
    es: "El modelo mencionó un retiro no respaldado por una coincidencia oficial confirmada.",
    ar: "ذكر النموذج استدعاءً غير مدعوم بتطابق رسمي مؤكد.",
    zh: "模型提到了无官方确认匹配支持的召回。",
    ja: "モデルは公式確認一致に裏付けられないリコールに言及しました。",
    ru: "Модель упомянула отзыв без официального подтверждённого совпадения.",
    pt: "O modelo mencionou um recall não respaldado por correspondência oficial confirmada.",
  },
  {
    en: "Unsupported claims were downgraded and are not shown as verified facts.",
    tr: "Desteklenmeyen iddialar düşürüldü ve doğrulanmış gerçek olarak gösterilmiyor.",
    de: "Nicht unterstützte Behauptungen wurden herabgestuft und nicht als Fakten gezeigt.",
    fr: "Les affirmations non supportées ont été rétrogradées et ne sont pas présentées comme des faits vérifiés.",
    es: "Las afirmaciones no respaldadas se degradaron y no se muestran como hechos verificados.",
    ar: "خُفّضت الادعاءات غير المدعومة ولا تُعرض كحقائق verified.",
    zh: "不支持的声明已降级，不会作为已验证事实显示。",
    ja: "支持されない主張は降格され、検証済み事実として表示されません。",
    ru: "Неподдерживаемые утверждения понижены и не показываются как проверенные факты.",
    pt: "Alegações não suportadas foram rebaixadas e não são exibidas como fatos verificados.",
  },
  {
    en: "Contradictory evidence requires human review.",
    tr: "Çelişkili kanıtlar insan incelemesi gerektiriyor.",
    de: "Widersprüchliche Beweise erfordern menschliche Prüfung.",
    fr: "Des preuves contradictoires nécessitent un examen humain.",
    es: "La evidencia contradictoria requiere revisión humana.",
    ar: "الأدلة المتناقضة تتطلب مراجعة بشرية.",
    zh: "矛盾证据需要人工审核。",
    ja: "矛盾する証拠には人間のレビューが必要です。",
    ru: "Противоречивые доказательства требуют проверки человеком.",
    pt: "Evidência contraditória requer revisão humana.",
  },
  {
    en: "No supporting evidence was persisted for this analysis.",
    tr: "Bu analiz için destekleyici kanıt kaydedilmedi.",
    de: "Für diese Analyse wurden keine unterstützenden Beweise gespeichert.",
    fr: "Aucune preuve de support n'a été persistée pour cette analyse.",
    es: "No se persistió evidencia de apoyo para este análisis.",
    ar: "لم تُحفظ أدلة داعمة لهذا التحليل.",
    zh: "本分析未保存支持性证据。",
    ja: "この分析には支持証拠が保存されませんでした。",
    ru: "Для этого анализа не сохранены поддерживающие доказательства.",
    pt: "Nenhuma evidência de apoio foi persistida para esta análise.",
  },
  {
    en: "Overconfident language was stripped from the user-facing conclusion.",
    tr: "Aşırı güvenli ifadeler kullanıcıya yönelik sonuçtan çıkarıldı.",
    de: "Zu selbstsichere Formulierungen wurden aus der Nutzer-Zusammenfassung entfernt.",
    fr: "Un langage trop confiant a été retiré de la conclusion utilisateur.",
    es: "Se eliminó lenguaje demasiado confiado de la conclusión para el usuario.",
    ar: "أُزيلت العبارات المفرطة في الثقة من الخلاصة الموجهة للمستخدم.",
    zh: "过度自信的表述已从面向用户的结论中移除。",
    ja: "過度に自信のある表現はユーザー向け結論から削除されました。",
    ru: "Чрезмерно уверенные формулировки удалены из пользовательского вывода.",
    pt: "Linguagem excessivamente confiante foi removida da conclusão ao usuário.",
  },
  {
    en: "Positive review or rating signals.",
    tr: "Olumlu yorum veya puan sinyalleri.",
  },
  {
    en: "Negative review or rating signals.",
    tr: "Olumsuz yorum veya puan sinyalleri.",
  },
  {
    en: "Repeated complaint theme.",
    tr: "Tekrarlanan şikayet teması.",
  },
  {
    en: "SAFETY signal from reviews.",
    tr: "Yorumlardan güvenlik sinyali.",
  },
  {
    en: "QUALITY signal from reviews.",
    tr: "Yorumlardan kalite sinyali.",
  },
  {
    en: "DURABILITY signal from reviews.",
    tr: "Yorumlardan dayanıklılık sinyali.",
  },
  {
    en: "USABILITY signal from reviews.",
    tr: "Yorumlardan kullanım sinyali.",
  },
  {
    en: "ASSEMBLY signal from reviews.",
    tr: "Yorumlardan kurulum sinyali.",
  },
  {
    en: "AGE signal from reviews.",
    tr: "Yorumlardan yaş uyumu sinyali.",
  },
  {
    en: "POSITIVE signal from reviews.",
    tr: "Yorumlardan olumlu sinyal.",
  },
  {
    en: "NEGATIVE signal from reviews.",
    tr: "Yorumlardan olumsuz sinyal.",
  },
  {
    en: "REPEATED signal from reviews.",
    tr: "Yorumlardan tekrarlanan şikayet sinyali.",
  },
  {
    en: "A cited source does not match persisted evidence.",
    tr: "Atıf yapılan kaynak, kaydedilmiş kanıtla eşleşmiyor.",
    de: "Eine zitierte Quelle passt nicht zu gespeicherten Beweisen.",
    fr: "Une source citée ne correspond pas aux preuves persistées.",
    es: "Una fuente citada no coincide con la evidencia persistida.",
    ar: "المصدر الم cited لا يطابق الأدلة المحفوظة.",
    zh: "引用的来源与已保存证据不匹配。",
    ja: "引用ソースは保存された証拠と一致しません。",
    ru: "Указанный источник не соответствует сохранённым доказательствам.",
    pt: "Uma fonte citada não corresponde à evidência persistida.",
  },
];

export function phraseText(phrase: PolicyPhrase, locale: Locale): string {
  return phrase[locale] ?? phrase.en;
}
